// <auto-generated />
namespace FiestaLibReloaded.Networking.Enums;

/// <summary>Opcodes for the BOOTH department (0x1A).</summary>
public enum BoothOpcode : ushort
{
    Null = 0,
    OpenReq = 1,
    OpenAck = 2,
    SomeoneopenCmd = 3,
    CloseReq = 4,
    CloseAck = 5,
    SomeonecloseCmd = 6,
    EntryReq = 7,
    EntrySellAck = 8,
    EntryBuyAck = 9,
    RefreshReq = 10,
    RefreshSellAck = 11,
    RefreshBuyAck = 12,
    ItemtradeReq = 13,
    ItemtradeAck = 14,
    BuyrefreshCmd = 15,
    InteriorstartReq = 16,
    InteriorstartAck = 17,
    SomeoneinteriorstartCmd = 18,
    SearchItemListCategorizedReq = 19,
    SearchItemListCategorizedAck = 20,
    SearchBoothPositionReq = 21,
    SearchBoothPositionAck = 22,
    SearchBoothClosedCmd = 23,
}
