// <auto-generated />
namespace FiestaLibReloaded.Networking.Enums;

/// <summary>Opcodes for the CHARGED department (0x24).</summary>
public enum ChargedOpcode : ushort
{
    Null = 0,
    SetbuffCmd = 1,
    ResetbuffCmd = 2,
    BuffstartCmd = 3,
    BuffterminateCmd = 4,
    StatInitializeDbReq = 5,
    SkillempowInitializeDbReq = 6,
    StatInitializeDbSucAck = 7,
    SkillempowInitializeDbSucAck = 8,
    StatInitializeDbFailAck = 9,
    SkillempowInitializeDbFailAck = 10,
    DeleteweapontitleCmd = 11,
    StatInitializeSucCmd = 12,
    SkillempowInitializeSucCmd = 13,
    StatInitializeFailCmd = 14,
    SkillempowInitializeFailCmd = 15,
    BoothslotsizeCmd = 16,
}
