// <auto-generated />
namespace FiestaLibReloaded.Networking.Enums;

/// <summary>Opcodes for the CT department (0x18).</summary>
public enum CtOpcode : ushort
{
    Null = 0,
    SetCurrentReq = 1,
    SetCurrentAck = 2,
    SetSomeonechangeCmd = 3,
    SetCmd = 4,
    DbSetCmd = 5,
    CharttingCmd = 6,
    AddFriendCmd = 7,
    SetCurrentDbCmd = 8,
    LuascriptSetWorldCmd = 9,
    LuascriptSetZoneCmd = 10,
}
