// <auto-generated />
namespace FiestaLibReloaded.Networking.Enums;

/// <summary>Opcodes for the PET department (0x35).</summary>
public enum PetOpcode : ushort
{
    Null = 0,
    SetTendencyDbReq = 1,
    SetNameDbReq = 3,
    SetNameDbAck = 4,
    AskNewNameReq = 5,
    AskNewNameAck = 6,
    SetNameReq = 7,
    SetNameAck = 8,
    SetNameCancelReq = 9,
    SetNameCancelAck = 10,
    LoadInfoDbReq = 11,
    LoadInfoDbAck = 12,
    CreateDbReq = 13,
    CreateDbAck = 14,
    RemoveDbReq = 15,
    RemoveDbAck = 16,
    UseItemFailAck = 17,
    LinkResummonCmd = 18,
    SetNameCmd = 19,
}
