// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Announce (0x19) | Opcode: 2 | Full: 0x1902
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Announce, 2)]
public class PROTO_NC_ANNOUNCE_W2C_CMD : IFiestaPacketBody
{
    public ANNOUNCE_MESSAGE AnnounceMessage = new();

    public void Read(BinaryReader reader)
    {
        AnnounceMessage.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        AnnounceMessage.Write(writer);
    }
}

/// <summary>
/// Department: Announce (0x19) | Opcode: 1 | Full: 0x1901
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Announce, 1)]
public class PROTO_NC_ANNOUNCE_Z2W_CMD : IFiestaPacketBody
{
    public ANNOUNCE_MESSAGE AnnounceMessage = new();

    public void Read(BinaryReader reader)
    {
        AnnounceMessage.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        AnnounceMessage.Write(writer);
    }
}

