// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 24 | Full: 0x0718
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 24)]
public class PROTO_NC_BRIEFINFO_ABSTATE_CHANGE_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ABSTATE_INFORMATION info = new();

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        info.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        info.Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 25 | Full: 0x0719
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 25)]
public class PROTO_NC_BRIEFINFO_ABSTATE_CHANGE_LIST_CMD : IFiestaPacketBody
{
    public ushort handle;
    public byte count;
    public ABSTATE_INFORMATION[] infoList = [];

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        count = reader.ReadByte();
        infoList = new ABSTATE_INFORMATION[count];
        for (int i = 0; i < count; i++)
        {
            infoList[i] = new ABSTATE_INFORMATION();
            infoList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(count);
        for (int i = 0; i < infoList.Length; i++)
            infoList[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 14 | Full: 0x070E
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 14)]
public class PROTO_NC_BRIEFINFO_BRIEFINFODELETE_CMD : IFiestaPacketBody
{
    public ushort hnd;

    public void Read(BinaryReader reader)
    {
        hnd = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hnd);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 15 | Full: 0x070F
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 15)]
public class PROTO_NC_BRIEFINFO_BUILDDOOR_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ushort mobid;
    public SHINE_COORD_TYPE coord = new();
    public byte doorstate;
    public Name8 blockindex = new();
    public ushort scale;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        mobid = reader.ReadUInt16();
        coord.Read(reader);
        doorstate = reader.ReadByte();
        blockindex.Read(reader);
        scale = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(mobid);
        coord.Write(writer);
        writer.Write(doorstate);
        blockindex.Write(writer);
        writer.Write(scale);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 2 | Full: 0x0702
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 2)]
public class PROTO_NC_BRIEFINFO_CHANGEDECORATE_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ushort item;
    public byte nSlotNum;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        item = reader.ReadUInt16();
        nSlotNum = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(item);
        writer.Write(nSlotNum);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 3 | Full: 0x0703
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 3)]
public class PROTO_NC_BRIEFINFO_CHANGEUPGRADE_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ushort item;
    public byte upgrade;
    public byte nSlotNum;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        item = reader.ReadUInt16();
        upgrade = reader.ReadByte();
        nSlotNum = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(item);
        writer.Write(upgrade);
        writer.Write(nSlotNum);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 5 | Full: 0x0705
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 5)]
public class PROTO_NC_BRIEFINFO_CHANGEWEAPON_CMD : IFiestaPacketBody
{
    public PROTO_NC_BRIEFINFO_CHANGEUPGRADE_CMD upgradeinfo = new();
    public ushort currentmobid;
    public byte currentkilllevel;

    public void Read(BinaryReader reader)
    {
        upgradeinfo.Read(reader);
        currentmobid = reader.ReadUInt16();
        currentkilllevel = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        upgradeinfo.Write(writer);
        writer.Write(currentmobid);
        writer.Write(currentkilllevel);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 7 | Full: 0x0707
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 7)]
public class PROTO_NC_BRIEFINFO_CHARACTER_CMD : IFiestaPacketBody
{
    public byte charnum;
    public PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD[] chars = [];

    public void Read(BinaryReader reader)
    {
        charnum = reader.ReadByte();
        chars = new PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD[charnum];
        for (int i = 0; i < charnum; i++)
        {
            chars[i] = new PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD();
            chars[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(charnum);
        for (int i = 0; i < chars.Length; i++)
            chars[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 16 | Full: 0x0710
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 16)]
public class PROTO_NC_BRIEFINFO_DOOR_CMD : IFiestaPacketBody
{
    public byte doornum;
    public PROTO_NC_BRIEFINFO_BUILDDOOR_CMD[] doors = [];

    public void Read(BinaryReader reader)
    {
        doornum = reader.ReadByte();
        doors = new PROTO_NC_BRIEFINFO_BUILDDOOR_CMD[doornum];
        for (int i = 0; i < doornum; i++)
        {
            doors[i] = new PROTO_NC_BRIEFINFO_BUILDDOOR_CMD();
            doors[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(doornum);
        for (int i = 0; i < doors.Length; i++)
            doors[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 10 | Full: 0x070A
/// sizeof = 15
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 10)]
public class PROTO_NC_BRIEFINFO_DROPEDITEM_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ushort itemid;
    public SHINE_XY_TYPE location = new();
    public ushort dropmobhandle;
    // PROTO_NC_BRIEFINFO_DROPEDITEM_CMD::<unnamed-type-attr> attr at offset 14 (unsupported type)

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        itemid = reader.ReadUInt16();
        location.Read(reader);
        dropmobhandle = reader.ReadUInt16();
        reader.ReadBytes(1); // skip PROTO_NC_BRIEFINFO_DROPEDITEM_CMD::<unnamed-type-attr> attr
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(itemid);
        location.Write(writer);
        writer.Write(dropmobhandle);
        writer.Write(new byte[1]); // skip PROTO_NC_BRIEFINFO_DROPEDITEM_CMD::<unnamed-type-attr> attr
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 18 | Full: 0x0712
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 18)]
public class PROTO_NC_BRIEFINFO_EFFECT_CMD : IFiestaPacketBody
{
    public byte effectnum;
    public PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD[] effects = [];

    public void Read(BinaryReader reader)
    {
        effectnum = reader.ReadByte();
        effects = new PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD[effectnum];
        for (int i = 0; i < effectnum; i++)
        {
            effects[i] = new PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD();
            effects[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(effectnum);
        for (int i = 0; i < effects.Length; i++)
            effects[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 17 | Full: 0x0711
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 17)]
public class PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD : IFiestaPacketBody
{
    public ushort handle;
    public Name8 effectname = new();
    public SHINE_COORD_TYPE coord = new();
    public ushort detach;
    public ushort scale;
    // PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD::<unnamed-type-flag> flag at offset 47 (unsupported type)

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        effectname.Read(reader);
        coord.Read(reader);
        detach = reader.ReadUInt16();
        scale = reader.ReadUInt16();
        reader.ReadBytes(1); // skip PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD::<unnamed-type-flag> flag
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        effectname.Write(writer);
        coord.Write(writer);
        writer.Write(detach);
        writer.Write(scale);
        writer.Write(new byte[1]); // skip PROTO_NC_BRIEFINFO_EFFECTBLAST_CMD::<unnamed-type-flag> flag
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 1 | Full: 0x0701
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 1)]
public class PROTO_NC_BRIEFINFO_INFORM_CMD : IFiestaPacketBody
{
    public ushort nMyHnd;
    public NETCOMMAND ReceiveNetCommand = new();
    public ushort hnd;

    public void Read(BinaryReader reader)
    {
        nMyHnd = reader.ReadUInt16();
        ReceiveNetCommand.Read(reader);
        hnd = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMyHnd);
        ReceiveNetCommand.Write(writer);
        writer.Write(hnd);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 11 | Full: 0x070B
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 11)]
public class PROTO_NC_BRIEFINFO_ITEMONFIELD_CMD : IFiestaPacketBody
{
    public byte itemnum;
    public PROTO_NC_BRIEFINFO_DROPEDITEM_CMD[] items = [];

    public void Read(BinaryReader reader)
    {
        itemnum = reader.ReadByte();
        items = new PROTO_NC_BRIEFINFO_DROPEDITEM_CMD[itemnum];
        for (int i = 0; i < itemnum; i++)
        {
            items[i] = new PROTO_NC_BRIEFINFO_DROPEDITEM_CMD();
            items[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemnum);
        for (int i = 0; i < items.Length; i++)
            items[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 6 | Full: 0x0706
/// sizeof = 235
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 6)]
public class PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD : IFiestaPacketBody
{
    public ushort handle;
    public Name5 charid = new();
    public SHINE_COORD_TYPE coord = new();
    public byte mode;
    public byte chrclass;
    public PROTO_AVATAR_SHAPE_INFO shape = new();
    // PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD::<unnamed-type-shapedata> shapedata at offset 37 (unsupported type)
    public ushort polymorph;
    public STOPEMOTICON_DESCRIPT emoticon = new();
    public CHARTITLE_BRIEFINFO chartitle = new();
    public ABNORMAL_STATE_BIT abstatebit = new();
    public uint myguild;
    public byte type;
    public byte isGuildAcademyMember;
    public byte IsAutoPick;
    public byte Level;
    public sbyte[] sAnimation = new sbyte[32];
    public ushort nMoverHnd;
    public byte nMoverSlot;
    public byte nKQTeamType;
    public byte IsUseItemMinimon;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        charid.Read(reader);
        coord.Read(reader);
        mode = reader.ReadByte();
        chrclass = reader.ReadByte();
        shape.Read(reader);
        reader.ReadBytes(45); // skip PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD::<unnamed-type-shapedata> shapedata
        polymorph = reader.ReadUInt16();
        emoticon.Read(reader);
        chartitle.Read(reader);
        abstatebit.Read(reader);
        myguild = reader.ReadUInt32();
        type = reader.ReadByte();
        isGuildAcademyMember = reader.ReadByte();
        IsAutoPick = reader.ReadByte();
        Level = reader.ReadByte();
        for (int i = 0; i < 32; i++)
            sAnimation[i] = reader.ReadSByte();
        nMoverHnd = reader.ReadUInt16();
        nMoverSlot = reader.ReadByte();
        nKQTeamType = reader.ReadByte();
        IsUseItemMinimon = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        charid.Write(writer);
        coord.Write(writer);
        writer.Write(mode);
        writer.Write(chrclass);
        shape.Write(writer);
        writer.Write(new byte[45]); // skip PROTO_NC_BRIEFINFO_LOGINCHARACTER_CMD::<unnamed-type-shapedata> shapedata
        writer.Write(polymorph);
        emoticon.Write(writer);
        chartitle.Write(writer);
        abstatebit.Write(writer);
        writer.Write(myguild);
        writer.Write(type);
        writer.Write(isGuildAcademyMember);
        writer.Write(IsAutoPick);
        writer.Write(Level);
        for (int i = 0; i < 32; i++)
            writer.Write(sAnimation[i]);
        writer.Write(nMoverHnd);
        writer.Write(nMoverSlot);
        writer.Write(nKQTeamType);
        writer.Write(IsUseItemMinimon);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 13 | Full: 0x070D
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 13)]
public class PROTO_NC_BRIEFINFO_MAGICFIELDINFO_CMD : IFiestaPacketBody
{
    public byte magicfields;
    public PROTO_NC_BRIEFINFO_MAGICFIELDSPREAD_CMD[] magicfield = [];

    public void Read(BinaryReader reader)
    {
        magicfields = reader.ReadByte();
        magicfield = new PROTO_NC_BRIEFINFO_MAGICFIELDSPREAD_CMD[magicfields];
        for (int i = 0; i < magicfields; i++)
        {
            magicfield[i] = new PROTO_NC_BRIEFINFO_MAGICFIELDSPREAD_CMD();
            magicfield[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(magicfields);
        for (int i = 0; i < magicfield.Length; i++)
            magicfield[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 12 | Full: 0x070C
/// sizeof = 16
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 12)]
public class PROTO_NC_BRIEFINFO_MAGICFIELDSPREAD_CMD : IFiestaPacketBody
{
    public ushort handle;
    public ushort caster;
    public ushort skillid;
    public SHINE_XY_TYPE location = new();
    public ushort radious;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        caster = reader.ReadUInt16();
        skillid = reader.ReadUInt16();
        location.Read(reader);
        radious = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(caster);
        writer.Write(skillid);
        location.Write(writer);
        writer.Write(radious);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 20 | Full: 0x0714
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 20)]
public class PROTO_NC_BRIEFINFO_MINIHOUSE_CMD : IFiestaPacketBody
{
    public byte minihouses;
    public PROTO_NC_BRIEFINFO_MINIHOUSEBUILD_CMD[] minihouse = [];

    public void Read(BinaryReader reader)
    {
        minihouses = reader.ReadByte();
        minihouse = new PROTO_NC_BRIEFINFO_MINIHOUSEBUILD_CMD[minihouses];
        for (int i = 0; i < minihouses; i++)
        {
            minihouse[i] = new PROTO_NC_BRIEFINFO_MINIHOUSEBUILD_CMD();
            minihouse[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(minihouses);
        for (int i = 0; i < minihouse.Length; i++)
            minihouse[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 19 | Full: 0x0713
/// sizeof = 64
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 19)]
public class PROTO_NC_BRIEFINFO_MINIHOUSEBUILD_CMD : IFiestaPacketBody
{
    public ushort handle;
    public CHARBRIEFINFO_CAMP camp = new();
    public Name5 charid = new();
    public SHINE_COORD_TYPE coord = new();
    public sbyte[] title = new sbyte[21];

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        camp.Read(reader);
        charid.Read(reader);
        coord.Read(reader);
        for (int i = 0; i < 21; i++)
            title[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        camp.Write(writer);
        charid.Write(writer);
        coord.Write(writer);
        for (int i = 0; i < 21; i++)
            writer.Write(title[i]);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 9 | Full: 0x0709
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 9)]
public class PROTO_NC_BRIEFINFO_MOB_CMD : IFiestaPacketBody
{
    public byte mobnum;
    public PROTO_NC_BRIEFINFO_REGENMOB_CMD[] mobs = [];

    public void Read(BinaryReader reader)
    {
        mobnum = reader.ReadByte();
        mobs = new PROTO_NC_BRIEFINFO_REGENMOB_CMD[mobnum];
        for (int i = 0; i < mobnum; i++)
        {
            mobs[i] = new PROTO_NC_BRIEFINFO_REGENMOB_CMD();
            mobs[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mobnum);
        for (int i = 0; i < mobs.Length; i++)
            mobs[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 27 | Full: 0x071B
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 27)]
public class PROTO_NC_BRIEFINFO_MOVER_CMD : IFiestaPacketBody
{
    public byte nMoverNum;
    public PROTO_NC_BRIEFINFO_REGENMOVER_CMD[] Movers = [];

    public void Read(BinaryReader reader)
    {
        nMoverNum = reader.ReadByte();
        Movers = new PROTO_NC_BRIEFINFO_REGENMOVER_CMD[nMoverNum];
        for (int i = 0; i < nMoverNum; i++)
        {
            Movers[i] = new PROTO_NC_BRIEFINFO_REGENMOVER_CMD();
            Movers[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMoverNum);
        for (int i = 0; i < Movers.Length; i++)
            Movers[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 29 | Full: 0x071D
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 29)]
public class PROTO_NC_BRIEFINFO_PET_CMD : IFiestaPacketBody
{
    public byte nPetCnt;
    public PROTO_NC_BRIEFINFO_REGENPET_CMD[] Pets = [];

    public void Read(BinaryReader reader)
    {
        nPetCnt = reader.ReadByte();
        Pets = new PROTO_NC_BRIEFINFO_REGENPET_CMD[nPetCnt];
        for (int i = 0; i < nPetCnt; i++)
        {
            Pets[i] = new PROTO_NC_BRIEFINFO_REGENPET_CMD();
            Pets[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPetCnt);
        for (int i = 0; i < Pets.Length; i++)
            Pets[i].Write(writer);
    }
}

/// <summary>sizeof = 30</summary>
public class PROTO_NC_BRIEFINFO_PLAYER_INFO_APPEAR_CMD : IFiestaPacketBody
{
    public ushort nHnd;
    public Name5 sID = new();
    public CHARTITLE_BRIEFINFO CharTitle = new();
    public uint nGuildID;

    public void Read(BinaryReader reader)
    {
        nHnd = reader.ReadUInt16();
        sID.Read(reader);
        CharTitle.Read(reader);
        nGuildID = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHnd);
        sID.Write(writer);
        CharTitle.Write(writer);
        writer.Write(nGuildID);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 22 | Full: 0x0716
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 22)]
public class PROTO_NC_BRIEFINFO_PLAYER_LIST_INFO_APPEAR_CMD : IFiestaPacketBody
{
    public byte nPlayerCnt;
    public PROTO_NC_BRIEFINFO_PLAYER_INFO_APPEAR_CMD[] PlayerInfo = [];

    public void Read(BinaryReader reader)
    {
        nPlayerCnt = reader.ReadByte();
        PlayerInfo = new PROTO_NC_BRIEFINFO_PLAYER_INFO_APPEAR_CMD[nPlayerCnt];
        for (int i = 0; i < nPlayerCnt; i++)
        {
            PlayerInfo[i] = new PROTO_NC_BRIEFINFO_PLAYER_INFO_APPEAR_CMD();
            PlayerInfo[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPlayerCnt);
        for (int i = 0; i < PlayerInfo.Length; i++)
            PlayerInfo[i].Write(writer);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 8 | Full: 0x0708
/// sizeof = 149
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 8)]
public class PROTO_NC_BRIEFINFO_REGENMOB_CMD : IFiestaPacketBody
{
    public ushort handle;
    public byte mode;
    public ushort mobid;
    public SHINE_COORD_TYPE coord = new();
    public byte flagstate;
    // PROTO_NC_BRIEFINFO_REGENMOB_CMD::<unnamed-type-flag> flag at offset 15 (unsupported type)
    public sbyte[] sAnimation = new sbyte[32];
    public byte nAnimationLevel;
    public byte nKQTeamType;
    public byte bRegenAni;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        mode = reader.ReadByte();
        mobid = reader.ReadUInt16();
        coord.Read(reader);
        flagstate = reader.ReadByte();
        reader.ReadBytes(99); // skip PROTO_NC_BRIEFINFO_REGENMOB_CMD::<unnamed-type-flag> flag
        for (int i = 0; i < 32; i++)
            sAnimation[i] = reader.ReadSByte();
        nAnimationLevel = reader.ReadByte();
        nKQTeamType = reader.ReadByte();
        bRegenAni = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(mode);
        writer.Write(mobid);
        coord.Write(writer);
        writer.Write(flagstate);
        writer.Write(new byte[99]); // skip PROTO_NC_BRIEFINFO_REGENMOB_CMD::<unnamed-type-flag> flag
        for (int i = 0; i < 32; i++)
            writer.Write(sAnimation[i]);
        writer.Write(nAnimationLevel);
        writer.Write(nKQTeamType);
        writer.Write(bRegenAni);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 26 | Full: 0x071A
/// sizeof = 139
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 26)]
public class PROTO_NC_BRIEFINFO_REGENMOVER_CMD : IFiestaPacketBody
{
    public ushort nHandle;
    public uint nID;
    public uint nHP;
    public SHINE_COORD_TYPE nCoord = new();
    public ABNORMAL_STATE_BIT AbstateBit = new();
    public byte nGrade;
    public ushort[] nSlotHandle = new ushort[10];

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nID = reader.ReadUInt32();
        nHP = reader.ReadUInt32();
        nCoord.Read(reader);
        AbstateBit.Read(reader);
        nGrade = reader.ReadByte();
        for (int i = 0; i < 10; i++)
            nSlotHandle[i] = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nID);
        writer.Write(nHP);
        nCoord.Write(writer);
        AbstateBit.Write(writer);
        writer.Write(nGrade);
        for (int i = 0; i < 10; i++)
            writer.Write(nSlotHandle[i]);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 28 | Full: 0x071C
/// sizeof = 63
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 28)]
public class PROTO_NC_BRIEFINFO_REGENPET_CMD : IFiestaPacketBody
{
    public ushort nHandle;
    public uint nID;
    public SHINE_COORD_TYPE XYDir = new();
    public Name4 sPetName = new();
    public sbyte[] sAnimationIndex = new sbyte[32];

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nID = reader.ReadUInt32();
        XYDir.Read(reader);
        sPetName.Read(reader);
        for (int i = 0; i < 32; i++)
            sAnimationIndex[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nID);
        XYDir.Write(writer);
        sPetName.Write(writer);
        for (int i = 0; i < 32; i++)
            writer.Write(sAnimationIndex[i]);
    }
}

/// <summary>
/// Department: Briefinfo (0x07) | Opcode: 4 | Full: 0x0704
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Briefinfo, 4)]
public class PROTO_NC_BRIEFINFO_UNEQUIP_CMD : IFiestaPacketBody
{
    public ushort handle;
    public byte slot;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        slot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(slot);
    }
}

