// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Charsave (0x10) | Opcode: 17 | Full: 0x1011
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 17)]
public class PROTO_NC_CHARSAVE_2WLDMAN_ABSTATE_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public PROTO_NC_CHARSAVE_ABSTATE_REQ abstate = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        abstate.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        abstate.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 14 | Full: 0x100E
/// sizeof = 107
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 14)]
public class PROTO_NC_CHARSAVE_2WLDMAN_ALL_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public PROTO_NC_CHARSAVE_ALL_REQ all = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        all.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        all.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 50 | Full: 0x1032
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 50)]
public class PROTO_NC_CHARSAVE_2WLDMAN_CHAT_COLOR_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public byte nChatFontColorID;
    public byte nChatBalloonColorID;

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        nChatFontColorID = reader.ReadByte();
        nChatBalloonColorID = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        writer.Write(nChatFontColorID);
        writer.Write(nChatBalloonColorID);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 20 | Full: 0x1014
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 20)]
public class PROTO_NC_CHARSAVE_2WLDMAN_CHESTINFO_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public PROTO_NC_CHAR_CHESTINFO_REQ chest = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        chest.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        chest.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 44 | Full: 0x102C
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 44)]
public class PROTO_NC_CHARSAVE_2WLDMAN_COININFO_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public ulong nCoin;
    public ulong nExchangedCoin;
    public uint nCharNo;

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        nCoin = reader.ReadUInt64();
        nExchangedCoin = reader.ReadUInt64();
        nCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(nCoin);
        writer.Write(nExchangedCoin);
        writer.Write(nCharNo);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 21 | Full: 0x1015
/// sizeof = 11
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 21)]
public class PROTO_NC_CHARSAVE_2WLDMAN_GAME_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public uint nCharNo;
    public PROTO_GAMEDATA_CMD game = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
        game.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(nCharNo);
        game.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 19 | Full: 0x1013
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 19)]
public class PROTO_NC_CHARSAVE_2WLDMAN_ITEM_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public uint nCharNo;
    // PROTO_NC_CHARSAVE_2WLDMAN_ITEM_CMD::<unnamed-type-PacketOrder> PacketOrder at offset 6 (unsupported type)
    public byte nPartMark;
    public PROTO_ITEM_CMD itemstr = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
        reader.ReadBytes(1); // skip PROTO_NC_CHARSAVE_2WLDMAN_ITEM_CMD::<unnamed-type-PacketOrder> PacketOrder
        nPartMark = reader.ReadByte();
        itemstr.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(nCharNo);
        writer.Write(new byte[1]); // skip PROTO_NC_CHARSAVE_2WLDMAN_ITEM_CMD::<unnamed-type-PacketOrder> PacketOrder
        writer.Write(nPartMark);
        itemstr.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 52 | Full: 0x1034
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 52)]
public class PROTO_NC_CHARSAVE_2WLDMAN_ITEMACTIONCOOLTIME_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public PROTO_NC_CHARSAVE_ITEMACTIONCOOLTIME_ACK ActionCoolTime = new();

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        ActionCoolTime.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        ActionCoolTime.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 25 | Full: 0x1019
/// sizeof = 26
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 25)]
public class PROTO_NC_CHARSAVE_2WLDMAN_LINK_FROM_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public PROTO_NC_CHAR_LINKFROM_CMD linkfrom = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        linkfrom.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        linkfrom.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 23 | Full: 0x1017
/// sizeof = 18
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 23)]
public class PROTO_NC_CHARSAVE_2WLDMAN_MISC_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public ulong cen;
    public uint fame;
    public uint nCharNo;

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        cen = reader.ReadUInt64();
        fame = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(cen);
        writer.Write(fame);
        writer.Write(nCharNo);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 51 | Full: 0x1033
/// sizeof = 23
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 51)]
public class PROTO_NC_CHARSAVE_2WLDMAN_PET_LINK_RESUMMON_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public byte bDoResummon;
    public ulong xResummonCode;
    public ushort nSummonSlot;
    public uint nId;
    public uint nRegNum;

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        bDoResummon = reader.ReadByte();
        xResummonCode = reader.ReadUInt64();
        nSummonSlot = reader.ReadUInt16();
        nId = reader.ReadUInt32();
        nRegNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        writer.Write(bDoResummon);
        writer.Write(xResummonCode);
        writer.Write(nSummonSlot);
        writer.Write(nId);
        writer.Write(nRegNum);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 15 | Full: 0x100F
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 15)]
public class PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DOING_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    // PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DOING_CMD::tagQUESTDOING questdoing at offset 2 (unsupported type)

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        reader.ReadBytes(6); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DOING_CMD::tagQUESTDOING questdoing
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(new byte[6]); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DOING_CMD::tagQUESTDOING questdoing
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 16 | Full: 0x1010
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 16)]
public class PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DONE_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    // PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DONE_CMD::tagQUESTDONE questdone at offset 2 (unsupported type)

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        reader.ReadBytes(12); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DONE_CMD::tagQUESTDONE questdone
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(new byte[12]); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_DONE_CMD::tagQUESTDONE questdone
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 41 | Full: 0x1029
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 41)]
public class PROTO_NC_CHARSAVE_2WLDMAN_QUEST_READ_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    // PROTO_NC_CHARSAVE_2WLDMAN_QUEST_READ_CMD::tagQUESTREAD questread at offset 2 (unsupported type)

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        reader.ReadBytes(6); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_READ_CMD::tagQUESTREAD questread
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(new byte[6]); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_READ_CMD::tagQUESTREAD questread
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 43 | Full: 0x102B
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 43)]
public class PROTO_NC_CHARSAVE_2WLDMAN_QUEST_REPEAT_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    // PROTO_NC_CHARSAVE_2WLDMAN_QUEST_REPEAT_CMD::tagQUESTREPEAT questrepeat at offset 2 (unsupported type)

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        reader.ReadBytes(6); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_REPEAT_CMD::tagQUESTREPEAT questrepeat
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(new byte[6]); // skip PROTO_NC_CHARSAVE_2WLDMAN_QUEST_REPEAT_CMD::tagQUESTREPEAT questrepeat
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 42 | Full: 0x102A
/// sizeof = 17
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 42)]
public class PROTO_NC_CHARSAVE_2WLDMAN_SINGLE_OPTION_CMD : IFiestaPacketBody
{
    public ushort WmHandle;
    public uint chrregnum;
    public int resttime;
    public byte autopick;
    public byte mystery_vault;
    public uint nChatBan;
    public byte bFirstJoin;

    public void Read(BinaryReader reader)
    {
        WmHandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        resttime = reader.ReadInt32();
        autopick = reader.ReadByte();
        mystery_vault = reader.ReadByte();
        nChatBan = reader.ReadUInt32();
        bFirstJoin = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(WmHandle);
        writer.Write(chrregnum);
        writer.Write(resttime);
        writer.Write(autopick);
        writer.Write(mystery_vault);
        writer.Write(nChatBan);
        writer.Write(bFirstJoin);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 18 | Full: 0x1012
/// sizeof = 13
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 18)]
public class PROTO_NC_CHARSAVE_2WLDMAN_SKILL_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public PARTMARK PartMark = new();
    public ushort nMaxNum;
    public PROTO_NC_CHARSAVE_SKILL_REQ skill = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        PartMark.Read(reader);
        nMaxNum = reader.ReadUInt16();
        skill.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        PartMark.Write(writer);
        writer.Write(nMaxNum);
        skill.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 22 | Full: 0x1016
/// sizeof = 1037
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 22)]
public class PROTO_NC_CHARSAVE_2WLDMAN_TITLE_CMD : IFiestaPacketBody
{
    public ushort wldmanhandle;
    public uint nCharNo;
    public CHARACTER_TITLE_READBLOCK CTData = new();

    public void Read(BinaryReader reader)
    {
        wldmanhandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
        CTData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wldmanhandle);
        writer.Write(nCharNo);
        CTData.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 7 | Full: 0x1007
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 7)]
public class PROTO_NC_CHARSAVE_ABSTATE_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();
    public ushort abstatenum;
    public ABSTATEREADBLOCK[] abstate = [];

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
        abstatenum = reader.ReadUInt16();
        abstate = new ABSTATEREADBLOCK[abstatenum];
        for (int i = 0; i < abstatenum; i++)
        {
            abstate[i] = new ABSTATEREADBLOCK();
            abstate[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
        writer.Write(abstatenum);
        for (int i = 0; i < abstate.Length; i++)
            abstate[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 2 | Full: 0x1002
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 2)]
public class PROTO_NC_CHARSAVE_ALL_ACK : IFiestaPacketBody
{
    public ushort bufferlocation;
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        bufferlocation = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(bufferlocation);
        writer.Write(chrregnum);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 1 | Full: 0x1001
/// sizeof = 105
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 1)]
public class PROTO_NC_CHARSAVE_ALL_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();
    public PROTO_NC_CHARSAVE_LEVEL_CMD level = new();
    public PROTO_NC_CHARSAVE_LOCATION_CMD location = new();
    public PROTO_NC_CHARSAVE_CHARSTAT_CMD stat = new();

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
        level.Read(reader);
        location.Read(reader);
        stat.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
        level.Write(writer);
        location.Write(writer);
        stat.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 13 | Full: 0x100D
/// sizeof = 34
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 13)]
public class PROTO_NC_CHARSAVE_CHARSTAT_CMD : IFiestaPacketBody
{
    public uint chrregnum;
    public uint CurPwrStone;
    public uint CurGrdStone;
    public uint CurHPStone;
    public uint CurSPStone;
    public uint CurHP;
    public uint CurSP;
    public CHARSTATDISTSTR statdistribute = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        CurPwrStone = reader.ReadUInt32();
        CurGrdStone = reader.ReadUInt32();
        CurHPStone = reader.ReadUInt32();
        CurSPStone = reader.ReadUInt32();
        CurHP = reader.ReadUInt32();
        CurSP = reader.ReadUInt32();
        statdistribute.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(CurPwrStone);
        writer.Write(CurGrdStone);
        writer.Write(CurHPStone);
        writer.Write(CurSPStone);
        writer.Write(CurHP);
        writer.Write(CurSP);
        statdistribute.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 49 | Full: 0x1031
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 49)]
public class PROTO_NC_CHARSAVE_CHAT_COLOR_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public byte nChatFontColorID;
    public byte nChatBalloonColorID;

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        nChatFontColorID = reader.ReadByte();
        nChatBalloonColorID = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        writer.Write(nChatFontColorID);
        writer.Write(nChatBalloonColorID);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 40 | Full: 0x1028
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 40)]
public class PROTO_NC_CHARSAVE_DB_UI_STATE_SAVE_ACK : IFiestaPacketBody
{
    public NETPACKETZONEHEADER header = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 39 | Full: 0x1027
/// sizeof = 7
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 39)]
public class PROTO_NC_CHARSAVE_DB_UI_STATE_SAVE_REQ : IFiestaPacketBody
{
    public NETPACKETZONEHEADER header = new();
    public byte btMysteryType;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        btMysteryType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(btMysteryType);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 36 | Full: 0x1024
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 36)]
public class PROTO_NC_CHARSAVE_ITEMACTIONCOOLTIME_ACK : IFiestaPacketBody
{
    public ushort num;
    public ActionCooltime[] group = [];

    public void Read(BinaryReader reader)
    {
        num = reader.ReadUInt16();
        group = new ActionCooltime[num];
        for (int i = 0; i < num; i++)
        {
            group[i] = new ActionCooltime();
            group[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(num);
        for (int i = 0; i < group.Length; i++)
            group[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 35 | Full: 0x1023
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 35)]
public class PROTO_NC_CHARSAVE_ITEMACTIONCOOLTIME_REQ : IFiestaPacketBody
{
    public ushort num;
    public ActionCooltime[] group = [];

    public void Read(BinaryReader reader)
    {
        num = reader.ReadUInt16();
        group = new ActionCooltime[num];
        for (int i = 0; i < num; i++)
        {
            group[i] = new ActionCooltime();
            group[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(num);
        for (int i = 0; i < group.Length; i++)
            group[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 4 | Full: 0x1004
/// sizeof = 17
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 4)]
public class PROTO_NC_CHARSAVE_LEVEL_CMD : IFiestaPacketBody
{
    public uint chrregnum;
    public byte level;
    public ulong exp;
    public uint fame;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        level = reader.ReadByte();
        exp = reader.ReadUInt64();
        fame = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(level);
        writer.Write(exp);
        writer.Write(fame);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 3 | Full: 0x1003
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 3)]
public class PROTO_NC_CHARSAVE_LOCATION_CMD : IFiestaPacketBody
{
    public uint chrregnum;
    public Name3 map = new();
    public SHINE_XY_TYPE coord = new();
    public uint kqhandle;
    public Name3 map_kq = new();
    public SHINE_XY_TYPE coord_kq = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        map.Read(reader);
        coord.Read(reader);
        kqhandle = reader.ReadUInt32();
        map_kq.Read(reader);
        coord_kq.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        map.Write(writer);
        coord.Write(writer);
        writer.Write(kqhandle);
        map_kq.Write(writer);
        coord_kq.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 24 | Full: 0x1018
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 24)]
public class PROTO_NC_CHARSAVE_PKCOUNT_CMD : IFiestaPacketBody
{
    public uint chrregnum;
    public uint pkcount;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        pkcount = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(pkcount);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 5 | Full: 0x1005
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 5)]
public class PROTO_NC_CHARSAVE_QUEST_DOING_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();
    public byte bNeedClear;
    public byte nNumOfDoingQuest;
    public PLAYER_QUEST_INFO[] QuestDoingArray = [];

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
        bNeedClear = reader.ReadByte();
        nNumOfDoingQuest = reader.ReadByte();
        QuestDoingArray = new PLAYER_QUEST_INFO[nNumOfDoingQuest];
        for (int i = 0; i < nNumOfDoingQuest; i++)
        {
            QuestDoingArray[i] = new PLAYER_QUEST_INFO();
            QuestDoingArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
        writer.Write(bNeedClear);
        writer.Write(nNumOfDoingQuest);
        for (int i = 0; i < QuestDoingArray.Length; i++)
            QuestDoingArray[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 26 | Full: 0x101A
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 26)]
public class PROTO_NC_CHARSAVE_REST_EXP_LAST_EXEC_TIME_SAVE_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 55 | Full: 0x1037
/// sizeof = 7
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 55)]
public class PROTO_NC_CHARSAVE_SELL_ITEM_INFO_CMD : IFiestaPacketBody
{
    public ushort nWorldHandle;
    public uint nCharNo;
    public byte NumOfSellItem;
    public PROTO_SELL_ITEM_INFO_SERVER[] SellItemList = [];

    public void Read(BinaryReader reader)
    {
        nWorldHandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
        NumOfSellItem = reader.ReadByte();
        SellItemList = new PROTO_SELL_ITEM_INFO_SERVER[NumOfSellItem];
        for (int i = 0; i < NumOfSellItem; i++)
        {
            SellItemList[i] = new PROTO_SELL_ITEM_INFO_SERVER();
            SellItemList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nWorldHandle);
        writer.Write(nCharNo);
        writer.Write(NumOfSellItem);
        for (int i = 0; i < SellItemList.Length; i++)
            SellItemList[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 34 | Full: 0x1022
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 34)]
public class PROTO_NC_CHARSAVE_SET_CHAT_BLOCK_SPAMER_DB_CMD : IFiestaPacketBody
{
    public uint CharNo;
    public uint BlockTime;
    public uint DelayTime;

    public void Read(BinaryReader reader)
    {
        CharNo = reader.ReadUInt32();
        BlockTime = reader.ReadUInt32();
        DelayTime = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharNo);
        writer.Write(BlockTime);
        writer.Write(DelayTime);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 33 | Full: 0x1021
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 33)]
public class PROTO_NC_CHARSAVE_SET_CHAT_BLOCK_SPAMER_WM_CMD : IFiestaPacketBody
{
    public ushort WmHandle;
    public uint CharNo;
    public uint BlockTime;
    public uint DelayTime;

    public void Read(BinaryReader reader)
    {
        WmHandle = reader.ReadUInt16();
        CharNo = reader.ReadUInt32();
        BlockTime = reader.ReadUInt32();
        DelayTime = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(WmHandle);
        writer.Write(CharNo);
        writer.Write(BlockTime);
        writer.Write(DelayTime);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 9 | Full: 0x1009
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 9)]
public class PROTO_NC_CHARSAVE_SKILL_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();
    public ushort number;
    public PROTO_SKILLREADBLOCK[] skill = [];

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
        number = reader.ReadUInt16();
        skill = new PROTO_SKILLREADBLOCK[number];
        for (int i = 0; i < number; i++)
        {
            skill[i] = new PROTO_SKILLREADBLOCK();
            skill[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
        writer.Write(number);
        for (int i = 0; i < skill.Length; i++)
            skill[i].Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 11 | Full: 0x100B
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 11)]
public class PROTO_NC_CHARSAVE_TITLE_REQ : IFiestaPacketBody
{
    public PROTO_NC_CHARSAVE_ALL_ACK handle = new();
    public CHARACTER_TITLE_DB_SAVE CTData = new();

    public void Read(BinaryReader reader)
    {
        handle.Read(reader);
        CTData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        handle.Write(writer);
        CTData.Write(writer);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 38 | Full: 0x1026
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 38)]
public class PROTO_NC_CHARSAVE_UI_STATE_SAVE_ACK : IFiestaPacketBody
{
    public ushort err;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 37 | Full: 0x1025
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 37)]
public class PROTO_NC_CHARSAVE_UI_STATE_SAVE_REQ : IFiestaPacketBody
{
    public byte btMysteryType;

    public void Read(BinaryReader reader)
    {
        btMysteryType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(btMysteryType);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 53 | Full: 0x1035
/// sizeof = 78
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 53)]
public class PROTO_NC_CHARSAVE_USEITEM_MINIMON_INFO_DB_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public USEITEM_MINIMON_INFO UseItemMinimonInfo = new();
    public byte[] DelSlotList_Normal = new byte[12];
    public byte[] DelSlotList_Charged = new byte[12];

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        UseItemMinimonInfo.Read(reader);
        DelSlotList_Normal = reader.ReadBytes(12);
        DelSlotList_Charged = reader.ReadBytes(12);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        UseItemMinimonInfo.Write(writer);
        writer.Write(DelSlotList_Normal, 0, 12);
        writer.Write(DelSlotList_Charged, 0, 12);
    }
}

/// <summary>
/// Department: Charsave (0x10) | Opcode: 54 | Full: 0x1036
/// sizeof = 56
/// </summary>
[FiestaOpcode(ProtocolCommand.Charsave, 54)]
public class PROTO_NC_CHARSAVE_USEITEM_MINIMON_INFO_WORLD_CMD : IFiestaPacketBody
{
    public ushort nWorldHandle;
    public uint nCharNo;
    public USEITEM_MINIMON_INFO UseItemMinimonInfo = new();

    public void Read(BinaryReader reader)
    {
        nWorldHandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
        UseItemMinimonInfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nWorldHandle);
        writer.Write(nCharNo);
        UseItemMinimonInfo.Write(writer);
    }
}

