// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 6</summary>
public class PROTO_NC_COLLECT_BOOKMARK_REGIST_ACK
{
    public ushort BookMarkSlot;
    public ushort CardID;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        BookMarkSlot = reader.ReadUInt16();
        CardID = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(BookMarkSlot);
        writer.Write(CardID);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_COLLECT_BOOKMARK_REGIST_DB_ACK
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort BookMarkSlot;
    public ushort CardID;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        BookMarkSlot = reader.ReadUInt16();
        CardID = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(BookMarkSlot);
        writer.Write(CardID);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_COLLECT_BOOKMARK_REGIST_DB_REQ
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort BookMarkSlot;
    public ushort CardID;

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        BookMarkSlot = reader.ReadUInt16();
        CardID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(BookMarkSlot);
        writer.Write(CardID);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_COLLECT_BOOKMARK_REGIST_REQ
{
    public ushort BookMarkSlot;
    public ushort CardID;

    public void Read(BinaryReader reader)
    {
        BookMarkSlot = reader.ReadUInt16();
        CardID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(BookMarkSlot);
        writer.Write(CardID);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 106</summary>
public class PROTO_NC_COLLECT_CARDOPEN_CMD
{
    public ushort err;
    public byte Slot;
    public SHINE_ITEM_STRUCT CardInform = new();

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        Slot = reader.ReadByte();
        CardInform.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        writer.Write(Slot);
        CardInform.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_COLLECT_CARDREGIST_ACK
{
    public byte invenslot;
    public ushort CardID;
    public byte Star;
    public uint Serial;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        invenslot = reader.ReadByte();
        CardID = reader.ReadUInt16();
        Star = reader.ReadByte();
        Serial = reader.ReadUInt32();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(invenslot);
        writer.Write(CardID);
        writer.Write(Star);
        writer.Write(Serial);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_COLLECT_CARDREGIST_REQ
{
    public byte invenslot;

    public void Read(BinaryReader reader)
    {
        invenslot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(invenslot);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 28</summary>
public class PROTO_NC_COLLECT_PEEPING_COLLECT_ACK
{
    public Name5 charname = new();
    public ushort err;
    public PROTO_NC_CHAR_CARDCOLLECT_CMD collection = new();

    public void Read(BinaryReader reader)
    {
        charname.Read(reader);
        err = reader.ReadUInt16();
        collection.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charname.Write(writer);
        writer.Write(err);
        collection.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 28</summary>
public class PROTO_NC_COLLECT_PEEPING_COLLECT_BOOKMARK_ACK
{
    public Name5 charname = new();
    public ushort err;
    public PROTO_NC_CHAR_CARDCOLLECT_BOOKMARK_CMD collectionview = new();

    public void Read(BinaryReader reader)
    {
        charname.Read(reader);
        err = reader.ReadUInt16();
        collectionview.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charname.Write(writer);
        writer.Write(err);
        collectionview.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_COLLECT_PEEPING_DB_COLLECT_ACK
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public Name5 targetcharname = new();
    public ushort err;
    public PROTO_NC_CHAR_CARDCOLLECT_CMD collection = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        targetcharname.Read(reader);
        err = reader.ReadUInt16();
        collection.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        targetcharname.Write(writer);
        writer.Write(err);
        collection.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_COLLECT_PEEPING_DB_COLLECT_BOOKMARK_ACK
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public Name5 targetcharname = new();
    public ushort err;
    public PROTO_NC_CHAR_CARDCOLLECT_BOOKMARK_CMD collectionview = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        targetcharname.Read(reader);
        err = reader.ReadUInt16();
        collectionview.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        targetcharname.Write(writer);
        writer.Write(err);
        collectionview.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 26</summary>
public class PROTO_NC_COLLECT_PEEPING_DB_REQ
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public Name5 targetcharname = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        targetcharname.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        targetcharname.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 20</summary>
public class PROTO_NC_COLLECT_PEEPING_REQ
{
    public Name5 charname = new();

    public void Read(BinaryReader reader)
    {
        charname.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charname.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 18</summary>
public class PROTO_NC_COLLECT_REGIST_ACK
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort lockindex;
    public PROTO_NC_COLLECT_CARDREGIST_ACK CardInfo = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        lockindex = reader.ReadUInt16();
        CardInfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(lockindex);
        CardInfo.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 26</summary>
public class PROTO_NC_COLLECT_REGIST_REQ
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort lockindex;
    public SHINE_ITEM_REGISTNUMBER CardKey = new();
    public PROTO_NC_COLLECT_CARDREGIST_ACK CardInfo = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        lockindex = reader.ReadUInt16();
        CardKey.Read(reader);
        CardInfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(lockindex);
        CardKey.Write(writer);
        CardInfo.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_COLLECT_REWARD_ACK
{
    public ushort RewardID;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        RewardID = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(RewardID);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_COLLECT_REWARD_DB_ACK
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort RewardID;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        RewardID = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(RewardID);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 119</summary>
public class PROTO_NC_COLLECT_REWARD_DB_REQ
{
    public uint clientregnum;
    public ushort clientzonehandle;
    public ushort RewardID;
    public ItemTotalInformation RewardItem = new();

    public void Read(BinaryReader reader)
    {
        clientregnum = reader.ReadUInt32();
        clientzonehandle = reader.ReadUInt16();
        RewardID = reader.ReadUInt16();
        RewardItem.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(clientregnum);
        writer.Write(clientzonehandle);
        writer.Write(RewardID);
        RewardItem.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_COLLECT_REWARD_REQ
{
    public ushort RewardID;
    public ushort RewardItem;

    public void Read(BinaryReader reader)
    {
        RewardID = reader.ReadUInt16();
        RewardItem = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(RewardID);
        writer.Write(RewardItem);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

