// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Event (0x34) | Opcode: 4 | Full: 0xD004
/// sizeof = 1365
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 4)]
public class PROTO_NC_EVENT_ADD_EVENT_ACK : IFiestaPacketBody
{
    public ushort nError;
    public GM_EVENT_DATA EventData = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        EventData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        EventData.Write(writer);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 3 | Full: 0xD003
/// sizeof = 1363
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 3)]
public class PROTO_NC_EVENT_ADD_EVENT_REQ : IFiestaPacketBody
{
    public GM_EVENT_DATA EventData = new();

    public void Read(BinaryReader reader)
    {
        EventData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        EventData.Write(writer);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 11 | Full: 0xD00B
/// sizeof = 1363
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 11)]
public class PROTO_NC_EVENT_ADD_UPDATE_EVENT_CMD : IFiestaPacketBody
{
    public GM_EVENT_DATA EventData = new();

    public void Read(BinaryReader reader)
    {
        EventData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        EventData.Write(writer);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 8 | Full: 0xD008
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 8)]
public class PROTO_NC_EVENT_DEL_EVENT_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nEventNo;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nEventNo = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nEventNo);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 12 | Full: 0xD00C
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 12)]
public class PROTO_NC_EVENT_DEL_EVENT_CMD : IFiestaPacketBody
{
    public ushort nEventNo;

    public void Read(BinaryReader reader)
    {
        nEventNo = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nEventNo);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 7 | Full: 0xD007
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 7)]
public class PROTO_NC_EVENT_DEL_EVENT_REQ : IFiestaPacketBody
{
    public ushort nEventNo;

    public void Read(BinaryReader reader)
    {
        nEventNo = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nEventNo);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 2 | Full: 0xD002
/// sizeof = 1370
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 2)]
public class PROTO_NC_EVENT_GET_ALL_EVENT_INFO_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nAllEventCnt;
    public ushort nPacketOrder;
    public GM_EVENT_DATA EventData = new();
    public byte bIsFlagAllReady;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nAllEventCnt = reader.ReadUInt16();
        nPacketOrder = reader.ReadUInt16();
        EventData.Read(reader);
        bIsFlagAllReady = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nAllEventCnt);
        writer.Write(nPacketOrder);
        EventData.Write(writer);
        writer.Write(bIsFlagAllReady);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 1 | Full: 0xD001
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 1)]
public class PROTO_NC_EVENT_GET_ALL_EVENT_INFO_REQ : IFiestaPacketBody
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 10 | Full: 0xD00A
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 10)]
public class PROTO_NC_EVENT_SET_ALL_READY_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nEventNo;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nEventNo = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nEventNo);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 9 | Full: 0xD009
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 9)]
public class PROTO_NC_EVENT_SET_ALL_READY_REQ : IFiestaPacketBody
{
    public ushort nEventNo;
    public byte bIsFlagAllReady;

    public void Read(BinaryReader reader)
    {
        nEventNo = reader.ReadUInt16();
        bIsFlagAllReady = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nEventNo);
        writer.Write(bIsFlagAllReady);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 6 | Full: 0xD006
/// sizeof = 1365
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 6)]
public class PROTO_NC_EVENT_UPDATE_EVENT_ACK : IFiestaPacketBody
{
    public ushort nError;
    public GM_EVENT_DATA EventData = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        EventData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        EventData.Write(writer);
    }
}

/// <summary>
/// Department: Event (0x34) | Opcode: 5 | Full: 0xD005
/// sizeof = 1363
/// </summary>
[FiestaOpcode(ProtocolCommand.Event, 5)]
public class PROTO_NC_EVENT_UPDATE_EVENT_REQ : IFiestaPacketBody
{
    public GM_EVENT_DATA EventData = new();

    public void Read(BinaryReader reader)
    {
        EventData.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        EventData.Write(writer);
    }
}

