// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Friend (0x15) | Opcode: 8 | Full: 0x1508
/// sizeof = 72
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 8)]
public class PROTO_NC_FRIEND_ADD_CMD : IFiestaPacketBody
{
    public PROTO_FRIEND_INFO friendinfo = new();

    public void Read(BinaryReader reader)
    {
        friendinfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        friendinfo.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 24 | Full: 0x1518
/// sizeof = 21
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 24)]
public class PROTO_NC_FRIEND_CLASS_CHANGE_CMD : IFiestaPacketBody
{
    public Name5 charid = new();
    public byte new_class;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        new_class = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        writer.Write(new_class);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 19 | Full: 0x1513
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 19)]
public class PROTO_NC_FRIEND_DB_DEL_ACK : IFiestaPacketBody
{
    public ushort handle_charno;
    public uint charno;
    public Name5 charid = new();
    public Name5 friendid = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        handle_charno = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        charid.Read(reader);
        friendid.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_charno);
        writer.Write(charno);
        charid.Write(writer);
        friendid.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 18 | Full: 0x1512
/// sizeof = 46
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 18)]
public class PROTO_NC_FRIEND_DB_DEL_REQ : IFiestaPacketBody
{
    public ushort handle_charno;
    public uint charno;
    public Name5 charid = new();
    public Name5 friendid = new();

    public void Read(BinaryReader reader)
    {
        handle_charno = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        charid.Read(reader);
        friendid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_charno);
        writer.Write(charno);
        charid.Write(writer);
        friendid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 21 | Full: 0x1515
/// sizeof = 84
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 21)]
public class PROTO_NC_FRIEND_DB_GET_ACK : IFiestaPacketBody
{
    public ushort handle_char;
    public uint charno;
    public uint friendno;
    public ushort err;
    public PROTO_FRIEND_INFO friendinfo = new();

    public void Read(BinaryReader reader)
    {
        handle_char = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        friendno = reader.ReadUInt32();
        err = reader.ReadUInt16();
        friendinfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_char);
        writer.Write(charno);
        writer.Write(friendno);
        writer.Write(err);
        friendinfo.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 20 | Full: 0x1514
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 20)]
public class PROTO_NC_FRIEND_DB_GET_REQ : IFiestaPacketBody
{
    public ushort handle_char;
    public uint charno;
    public uint friendno;

    public void Read(BinaryReader reader)
    {
        handle_char = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        friendno = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_char);
        writer.Write(charno);
        writer.Write(friendno);
    }
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_FRIEND_DB_POINT : IFiestaPacketBody
{
    public uint charregnum;
    public ushort friendpoint;
    public ushort diffpoint;

    public void Read(BinaryReader reader)
    {
        charregnum = reader.ReadUInt32();
        friendpoint = reader.ReadUInt16();
        diffpoint = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(charregnum);
        writer.Write(friendpoint);
        writer.Write(diffpoint);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 28 | Full: 0x151C
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 28)]
public class PROTO_NC_FRIEND_DB_POINT_CMD : IFiestaPacketBody
{
    public ushort numoffriend;
    public PROTO_NC_FRIEND_DB_POINT[] pointinfo = [];

    public void Read(BinaryReader reader)
    {
        numoffriend = reader.ReadUInt16();
        pointinfo = new PROTO_NC_FRIEND_DB_POINT[numoffriend];
        for (int i = 0; i < numoffriend; i++)
        {
            pointinfo[i] = new PROTO_NC_FRIEND_DB_POINT();
            pointinfo[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(numoffriend);
        for (int i = 0; i < pointinfo.Length; i++)
            pointinfo[i].Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 17 | Full: 0x1511
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 17)]
public class PROTO_NC_FRIEND_DB_SET_ACK : IFiestaPacketBody
{
    public ushort handle_charno;
    public ushort handle_friendno;
    public uint charno;
    public uint friendno;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        handle_charno = reader.ReadUInt16();
        handle_friendno = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        friendno = reader.ReadUInt32();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_charno);
        writer.Write(handle_friendno);
        writer.Write(charno);
        writer.Write(friendno);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 16 | Full: 0x1510
/// sizeof = 13
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 16)]
public class PROTO_NC_FRIEND_DB_SET_REQ : IFiestaPacketBody
{
    public ushort handle_charno;
    public ushort handle_friendno;
    public uint charno;
    public uint friendno;
    public byte flag;

    public void Read(BinaryReader reader)
    {
        handle_charno = reader.ReadUInt16();
        handle_friendno = reader.ReadUInt16();
        charno = reader.ReadUInt32();
        friendno = reader.ReadUInt32();
        flag = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle_charno);
        writer.Write(handle_friendno);
        writer.Write(charno);
        writer.Write(friendno);
        writer.Write(flag);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 6 | Full: 0x1506
/// sizeof = 42
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 6)]
public class PROTO_NC_FRIEND_DEL_ACK : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 12 | Full: 0x150C
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 12)]
public class PROTO_NC_FRIEND_DEL_CMD : IFiestaPacketBody
{
    public Name5 charid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 5 | Full: 0x1505
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 5)]
public class PROTO_NC_FRIEND_DEL_REQ : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 32 | Full: 0x1520
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 32)]
public class PROTO_NC_FRIEND_FIND_FRIENDS_ACK : IFiestaPacketBody
{
    public ushort error;
    public ushort numoffriend;
    public PROTO_FRIEND_INFO[] friendinfo = [];

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
        numoffriend = reader.ReadUInt16();
        friendinfo = new PROTO_FRIEND_INFO[numoffriend];
        for (int i = 0; i < numoffriend; i++)
        {
            friendinfo[i] = new PROTO_FRIEND_INFO();
            friendinfo[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
        writer.Write(numoffriend);
        for (int i = 0; i < friendinfo.Length; i++)
            friendinfo[i].Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 37 | Full: 0x1525
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 37)]
public class PROTO_NC_FRIEND_GET_DIFF_FRIEND_POINT_CMD : IFiestaPacketBody
{
    public ushort diffpoint;

    public void Read(BinaryReader reader)
    {
        diffpoint = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(diffpoint);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 15 | Full: 0x150F
/// sizeof = 21
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 15)]
public class PROTO_NC_FRIEND_LEVEL_CMD : IFiestaPacketBody
{
    public Name5 charid = new();
    public byte level;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        level = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        writer.Write(level);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 7 | Full: 0x1507
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 7)]
public class PROTO_NC_FRIEND_LIST_CMD : IFiestaPacketBody
{
    public byte numoffriend;
    public PROTO_FRIEND_INFO[] friendinfo = [];

    public void Read(BinaryReader reader)
    {
        numoffriend = reader.ReadByte();
        friendinfo = new PROTO_FRIEND_INFO[numoffriend];
        for (int i = 0; i < numoffriend; i++)
        {
            friendinfo[i] = new PROTO_FRIEND_INFO();
            friendinfo[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(numoffriend);
        for (int i = 0; i < friendinfo.Length; i++)
            friendinfo[i].Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 9 | Full: 0x1509
/// sizeof = 32
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 9)]
public class PROTO_NC_FRIEND_LOGIN_CMD : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name3 map = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        map.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        map.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 10 | Full: 0x150A
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 10)]
public class PROTO_NC_FRIEND_LOGOUT_CMD : IFiestaPacketBody
{
    public Name5 charid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 13 | Full: 0x150D
/// sizeof = 32
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 13)]
public class PROTO_NC_FRIEND_MAP_CMD : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name3 map = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        map.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        map.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 14 | Full: 0x150E
/// sizeof = 21
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 14)]
public class PROTO_NC_FRIEND_PARTY_CMD : IFiestaPacketBody
{
    public Name5 charid = new();
    public byte is_party;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        is_party = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        writer.Write(is_party);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 30 | Full: 0x151E
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 30)]
public class PROTO_NC_FRIEND_POINT_ACK : IFiestaPacketBody
{
    public ushort friendpoint;

    public void Read(BinaryReader reader)
    {
        friendpoint = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(friendpoint);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 11 | Full: 0x150B
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 11)]
public class PROTO_NC_FRIEND_REFUSE_CMD : IFiestaPacketBody
{
    public Name5 friendid = new();

    public void Read(BinaryReader reader)
    {
        friendid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        friendid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 2 | Full: 0x1502
/// sizeof = 42
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 2)]
public class PROTO_NC_FRIEND_SET_ACK : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 4 | Full: 0x1504
/// sizeof = 41
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 4)]
public class PROTO_NC_FRIEND_SET_CONFIRM_ACK : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();
    public byte accept_friend;

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
        accept_friend = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
        writer.Write(accept_friend);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 3 | Full: 0x1503
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 3)]
public class PROTO_NC_FRIEND_SET_CONFIRM_REQ : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 1 | Full: 0x1501
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 1)]
public class PROTO_NC_FRIEND_SET_REQ : IFiestaPacketBody
{
    public Name5 charid = new();
    public Name5 friendid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
        friendid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
        friendid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 36 | Full: 0x1524
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 36)]
public class PROTO_NC_FRIEND_SOMEONE_GET_SPECIALITEM_WORLD_CMD : IFiestaPacketBody
{
    public Name5 charid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 35 | Full: 0x1523
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 35)]
public class PROTO_NC_FRIEND_SOMEONE_GET_SPECIALITEM_ZONE_CMD : IFiestaPacketBody
{
    public Name5 charid = new();

    public void Read(BinaryReader reader)
    {
        charid.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        charid.Write(writer);
    }
}

/// <summary>
/// Department: Friend (0x15) | Opcode: 34 | Full: 0x1522
/// sizeof = 7
/// </summary>
[FiestaOpcode(ProtocolCommand.Friend, 34)]
public class PROTO_NC_FRIEND_UES_FRIEND_POINT_ACK : IFiestaPacketBody
{
    public ushort error;
    public ushort friendpoint;
    public ushort itemid;
    public byte numofitem;

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
        friendpoint = reader.ReadUInt16();
        itemid = reader.ReadUInt16();
        numofitem = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
        writer.Write(friendpoint);
        writer.Write(itemid);
        writer.Write(numofitem);
    }
}

