// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Item (0x0C) | Opcode: 75 | Full: 0x0C4B
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 75)]
public class PROTO_NC_ITEM_AUTO_ARRANGE_INVEN_ACK : IFiestaPacketBody
{
    public ushort err;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 112 | Full: 0x0C70
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 112)]
public class PROTO_NC_ITEM_BRACELET_UPGRADE_ACK : IFiestaPacketBody
{
    public ushort err;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 111 | Full: 0x0C6F
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 111)]
public class PROTO_NC_ITEM_BRACELET_UPGRADE_REQ : IFiestaPacketBody
{
    public byte equip;
    public byte raw;

    public void Read(BinaryReader reader)
    {
        equip = reader.ReadByte();
        raw = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(equip);
        writer.Write(raw);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 3 | Full: 0x0C03
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 3)]
public class PROTO_NC_ITEM_BUY_REQ : IFiestaPacketBody
{
    public ushort itemid;
    public uint lot;

    public void Read(BinaryReader reader)
    {
        itemid = reader.ReadUInt16();
        lot = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemid);
        writer.Write(lot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 1 | Full: 0x0C01
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 1)]
public class PROTO_NC_ITEM_CELLCHANGE_CMD : IFiestaPacketBody
{
    public ITEM_INVEN exchange = new();
    public ITEM_INVEN location = new();
    public SHINE_ITEM_VAR_STRUCT item = new();

    public void Read(BinaryReader reader)
    {
        exchange.Read(reader);
        location.Read(reader);
        item.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        exchange.Write(writer);
        location.Write(writer);
        item.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 35 | Full: 0x0C23
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 35)]
public class PROTO_NC_ITEM_CHARGED_WITHDRAW_ACK : IFiestaPacketBody
{
    public uint ItemOrderNo;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        ItemOrderNo = reader.ReadUInt32();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ItemOrderNo);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 34 | Full: 0x0C22
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 34)]
public class PROTO_NC_ITEM_CHARGED_WITHDRAW_REQ : IFiestaPacketBody
{
    public uint ItemOrderNo;

    public void Read(BinaryReader reader)
    {
        ItemOrderNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ItemOrderNo);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 33 | Full: 0x0C21
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 33)]
public class PROTO_NC_ITEM_CHARGEDINVENOPEN_ACK : IFiestaPacketBody
{
    public ushort ErrorCode;
    public byte nPartMark;
    public ushort NumOfChargedItem;
    public PROTO_CHARGED_ITEM_INFO[] ChargedItemInfoList = [];

    public void Read(BinaryReader reader)
    {
        ErrorCode = reader.ReadUInt16();
        nPartMark = reader.ReadByte();
        NumOfChargedItem = reader.ReadUInt16();
        ChargedItemInfoList = new PROTO_CHARGED_ITEM_INFO[NumOfChargedItem];
        for (int i = 0; i < NumOfChargedItem; i++)
        {
            ChargedItemInfoList[i] = new PROTO_CHARGED_ITEM_INFO();
            ChargedItemInfoList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ErrorCode);
        writer.Write(nPartMark);
        writer.Write(NumOfChargedItem);
        for (int i = 0; i < ChargedItemInfoList.Length; i++)
            ChargedItemInfoList[i].Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 32 | Full: 0x0C20
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 32)]
public class PROTO_NC_ITEM_CHARGEDINVENOPEN_REQ : IFiestaPacketBody
{
    public ushort page;

    public void Read(BinaryReader reader)
    {
        page = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(page);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 86 | Full: 0x0C56
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 86)]
public class PROTO_NC_ITEM_CHAT_COLOR_CHANGE_ACK : IFiestaPacketBody
{
    public ushort nError;
    public byte nChangeColorID;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nChangeColorID = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nChangeColorID);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 85 | Full: 0x0C55
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 85)]
public class PROTO_NC_ITEM_CHAT_COLOR_CHANGE_REQ : IFiestaPacketBody
{
    public byte nSlotNo;

    public void Read(BinaryReader reader)
    {
        nSlotNo = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nSlotNo);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 94 | Full: 0x0C5E
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 94)]
public class PROTO_NC_ITEM_CLASS_CHANGE_REQ : IFiestaPacketBody
{
    public byte nStuffSlotNo;

    public void Read(BinaryReader reader)
    {
        nStuffSlotNo = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nStuffSlotNo);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 29 | Full: 0x0C1D
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 29)]
public class PROTO_NC_ITEM_DEPOSIT_ACK : IFiestaPacketBody
{
    public ulong cen;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 28 | Full: 0x0C1C
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 28)]
public class PROTO_NC_ITEM_DEPOSIT_REQ : IFiestaPacketBody
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 59 | Full: 0x0C3B
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 59)]
public class PROTO_NC_ITEM_DICE_GAME_CMD : IFiestaPacketBody
{
    public ushort itemhandle;
    public int nGameTimesec;

    public void Read(BinaryReader reader)
    {
        itemhandle = reader.ReadUInt16();
        nGameTimesec = reader.ReadInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemhandle);
        writer.Write(nGameTimesec);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 63 | Full: 0x0C3F
/// sizeof = 28
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 63)]
public class PROTO_NC_ITEM_DICE_GAME_RESULT_CMD : IFiestaPacketBody
{
    public ushort error;
    public Name5 WinnerID = new();
    public int diceresult;
    public ushort PickItemID;

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
        WinnerID.Read(reader);
        diceresult = reader.ReadInt32();
        PickItemID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
        WinnerID.Write(writer);
        writer.Write(diceresult);
        writer.Write(PickItemID);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 61 | Full: 0x0C3D
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 61)]
public class PROTO_NC_ITEM_DICE_GAME_START_ACK : IFiestaPacketBody
{
    public ushort error;

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 62 | Full: 0x0C3E
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 62)]
public class PROTO_NC_ITEM_DICE_GAME_START_CMD : IFiestaPacketBody
{
    public ushort charhandle;
    public int diceresult;

    public void Read(BinaryReader reader)
    {
        charhandle = reader.ReadUInt16();
        diceresult = reader.ReadInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(charhandle);
        writer.Write(diceresult);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 60 | Full: 0x0C3C
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 60)]
public class PROTO_NC_ITEM_DICE_GAME_START_REQ : IFiestaPacketBody
{
    public ushort itemhandle;
    public byte IsYes;

    public void Read(BinaryReader reader)
    {
        itemhandle = reader.ReadUInt16();
        IsYes = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemhandle);
        writer.Write(IsYes);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 42 | Full: 0x0C2A
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 42)]
public class PROTO_NC_ITEM_DISMANTLE_REQ : IFiestaPacketBody
{
    public byte item;

    public void Read(BinaryReader reader)
    {
        item = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(item);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 7 | Full: 0x0C07
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 7)]
public class PROTO_NC_ITEM_DROP_REQ : IFiestaPacketBody
{
    public ITEM_INVEN slot = new();
    public uint lot;
    public SHINE_XY_TYPE loc = new();

    public void Read(BinaryReader reader)
    {
        slot.Read(reader);
        lot = reader.ReadUInt32();
        loc.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        slot.Write(writer);
        writer.Write(lot);
        loc.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 65 | Full: 0x0C41
/// sizeof = 7
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 65)]
public class PROTO_NC_ITEM_ENCHANT_ADD_GEM_ACK : IFiestaPacketBody
{
    public ushort err;
    public ITEM_INVEN equipment = new();
    public ushort GemID;
    public byte gemSocketIndex;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        equipment.Read(reader);
        GemID = reader.ReadUInt16();
        gemSocketIndex = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        equipment.Write(writer);
        writer.Write(GemID);
        writer.Write(gemSocketIndex);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 64 | Full: 0x0C40
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 64)]
public class PROTO_NC_ITEM_ENCHANT_ADD_GEM_REQ : IFiestaPacketBody
{
    public ITEM_INVEN equipment = new();
    public ITEM_INVEN gem = new();

    public void Read(BinaryReader reader)
    {
        equipment.Read(reader);
        gem.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        equipment.Write(writer);
        gem.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 69 | Full: 0x0C45
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 69)]
public class PROTO_NC_ITEM_ENCHANT_ADD_NEW_SOCKET_ACK : IFiestaPacketBody
{
    public ushort err;
    public ITEM_INVEN equipment = new();
    public byte socketCount;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        equipment.Read(reader);
        socketCount = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        equipment.Write(writer);
        writer.Write(socketCount);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 68 | Full: 0x0C44
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 68)]
public class PROTO_NC_ITEM_ENCHANT_ADD_NEW_SOCKET_REQ : IFiestaPacketBody
{
    public ITEM_INVEN equipment = new();
    public ITEM_INVEN drill = new();

    public void Read(BinaryReader reader)
    {
        equipment.Read(reader);
        drill.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        equipment.Write(writer);
        drill.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 67 | Full: 0x0C43
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 67)]
public class PROTO_NC_ITEM_ENCHANT_REMOVE_GEM_ACK : IFiestaPacketBody
{
    public ushort err;
    public ITEM_INVEN equipment = new();
    public byte gemSocketIndex;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        equipment.Read(reader);
        gemSocketIndex = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        equipment.Write(writer);
        writer.Write(gemSocketIndex);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 66 | Full: 0x0C42
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 66)]
public class PROTO_NC_ITEM_ENCHANT_REMOVE_GEM_REQ : IFiestaPacketBody
{
    public ITEM_INVEN equipment = new();
    public ITEM_INVEN remover = new();
    public byte gemSocketIndex;

    public void Read(BinaryReader reader)
    {
        equipment.Read(reader);
        remover.Read(reader);
        gemSocketIndex = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        equipment.Write(writer);
        remover.Write(writer);
        writer.Write(gemSocketIndex);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 70 | Full: 0x0C46
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 70)]
public class PROTO_NC_ITEM_ENCHANT_SET_GEM_LOT_CMD : IFiestaPacketBody
{
    public ITEM_INVEN equipment = new();
    public byte gemSocketIndex;
    public byte restCount;

    public void Read(BinaryReader reader)
    {
        equipment.Read(reader);
        gemSocketIndex = reader.ReadByte();
        restCount = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        equipment.Write(writer);
        writer.Write(gemSocketIndex);
        writer.Write(restCount);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 73 | Full: 0x0C49
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 73)]
public class PROTO_NC_ITEM_EQUIP_BELONGED_CANCEL_USE_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 72 | Full: 0x0C48
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 72)]
public class PROTO_NC_ITEM_EQUIP_BELONGED_CANCEL_USE_REQ : IFiestaPacketBody
{
    public byte nCancelItemInvenSlot;
    public byte nBelongedItemInvenSlot;

    public void Read(BinaryReader reader)
    {
        nCancelItemInvenSlot = reader.ReadByte();
        nBelongedItemInvenSlot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCancelItemInvenSlot);
        writer.Write(nBelongedItemInvenSlot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 15 | Full: 0x0C0F
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 15)]
public class PROTO_NC_ITEM_EQUIP_REQ : IFiestaPacketBody
{
    public byte slot;

    public void Read(BinaryReader reader)
    {
        slot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 2 | Full: 0x0C02
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 2)]
public class PROTO_NC_ITEM_EQUIPCHANGE_CMD : IFiestaPacketBody
{
    public ITEM_INVEN exchange = new();
    public byte location;
    public SHINE_ITEM_VAR_STRUCT item = new();

    public void Read(BinaryReader reader)
    {
        exchange.Read(reader);
        location = reader.ReadByte();
        item.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        exchange.Write(writer);
        writer.Write(location);
        item.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 50 | Full: 0x0C32
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 50)]
public class PROTO_NC_ITEM_GUILD_ACADEMY_REWARD_STORAGE_DEPOSIT_ACK : IFiestaPacketBody
{
    public ulong cen;
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(Error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 49 | Full: 0x0C31
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 49)]
public class PROTO_NC_ITEM_GUILD_ACADEMY_REWARD_STORAGE_DEPOSIT_REQ : IFiestaPacketBody
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 48 | Full: 0x0C30
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 48)]
public class PROTO_NC_ITEM_GUILD_ACADEMY_REWARD_STORAGE_WITHDRAW_ACK : IFiestaPacketBody
{
    public ulong cen;
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(Error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 47 | Full: 0x0C2F
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 47)]
public class PROTO_NC_ITEM_GUILD_ACADEMY_REWARD_STORAGE_WITHDRAW_REQ : IFiestaPacketBody
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 39 | Full: 0x0C27
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 39)]
public class PROTO_NC_ITEM_GUILD_STORAGE_WITHDRAW_ACK : IFiestaPacketBody
{
    public ulong cen;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 38 | Full: 0x0C26
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 38)]
public class PROTO_NC_ITEM_GUILD_STORAGE_WITHDRAW_REQ : IFiestaPacketBody
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 56 | Full: 0x0C38
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 56)]
public class PROTO_NC_ITEM_ITEMBREAK_CMD : IFiestaPacketBody
{
    public ITEM_INVEN slot = new();

    public void Read(BinaryReader reader)
    {
        slot.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        slot.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 104 | Full: 0x0C68
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 104)]
public class PROTO_NC_ITEM_MAPLINK_SCROLL_ACK : IFiestaPacketBody
{
    public ushort nError;
    public byte lvFrom;
    public byte lvto;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        lvFrom = reader.ReadByte();
        lvto = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(lvFrom);
        writer.Write(lvto);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 103 | Full: 0x0C67
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 103)]
public class PROTO_NC_ITEM_MAPLINK_SCROLL_REQ : IFiestaPacketBody
{
    // WM_Link targetMap at offset 0 (unsupported type)

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 52 | Full: 0x0C34
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 52)]
public class PROTO_NC_ITEM_MH_FURNITURE_ENDURE_KIT_USE_ACK : IFiestaPacketBody
{
    public ShineDateTime dEndEndureDate = new();
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        dEndEndureDate.Read(reader);
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        dEndEndureDate.Write(writer);
        writer.Write(Error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 51 | Full: 0x0C33
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 51)]
public class PROTO_NC_ITEM_MH_FURNITURE_ENDURE_KIT_USE_REQ : IFiestaPacketBody
{
    public byte nInvenSlot;
    public ushort nFurnitureHnd;

    public void Read(BinaryReader reader)
    {
        nInvenSlot = reader.ReadByte();
        nFurnitureHnd = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nInvenSlot);
        writer.Write(nFurnitureHnd);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 80 | Full: 0x0C50
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 80)]
public class PROTO_NC_ITEM_MINIMON_EQUIP_REQ : IFiestaPacketBody
{
    public byte nSlotNo;
    public byte nEquipSlot;

    public void Read(BinaryReader reader)
    {
        nSlotNo = reader.ReadByte();
        nEquipSlot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nSlotNo);
        writer.Write(nEquipSlot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 106 | Full: 0x0C6A
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 106)]
public class PROTO_NC_ITEM_MIX_ITEM_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 105 | Full: 0x0C69
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 105)]
public class PROTO_NC_ITEM_MIX_ITEM_REQ : IFiestaPacketBody
{
    public byte nSubRaw;
    public byte nRawLeft;
    public byte nRawRight;

    public void Read(BinaryReader reader)
    {
        nSubRaw = reader.ReadByte();
        nRawLeft = reader.ReadByte();
        nRawRight = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nSubRaw);
        writer.Write(nRawLeft);
        writer.Write(nRawRight);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 82 | Full: 0x0C52
/// sizeof = 108
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 82)]
public class PROTO_NC_ITEM_MOVER_UPGRADE_ACK : IFiestaPacketBody
{
    public ushort nError;
    public byte bRare;
    public byte bUpgrade;
    public byte nSlot;
    public ushort nItemID;
    public SHINE_ITEM_ATTRIBUTE ItemAttr = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        bRare = reader.ReadByte();
        bUpgrade = reader.ReadByte();
        nSlot = reader.ReadByte();
        nItemID = reader.ReadUInt16();
        ItemAttr.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(bRare);
        writer.Write(bUpgrade);
        writer.Write(nSlot);
        writer.Write(nItemID);
        ItemAttr.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 81 | Full: 0x0C51
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 81)]
public class PROTO_NC_ITEM_MOVER_UPGRADE_REQ : IFiestaPacketBody
{
    public byte nMainSlotNo;
    public byte nSubSlotNo;

    public void Read(BinaryReader reader)
    {
        nMainSlotNo = reader.ReadByte();
        nSubSlotNo = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMainSlotNo);
        writer.Write(nSubSlotNo);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 110 | Full: 0x0C6E
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 110)]
public class PROTO_NC_ITEM_NEW_UPGRADE_ACK : IFiestaPacketBody
{
    public ushort err;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 109 | Full: 0x0C6D
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 109)]
public class PROTO_NC_ITEM_NEW_UPGRADE_REQ : IFiestaPacketBody
{
    public byte equip;
    public byte raw;

    public void Read(BinaryReader reader)
    {
        equip = reader.ReadByte();
        raw = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(equip);
        writer.Write(raw);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 96 | Full: 0x0C60
/// sizeof = 11
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 96)]
public class PROTO_NC_ITEM_OPENCLASSCHANGEMENU_CMD : IFiestaPacketBody
{
    public byte nNewClass;
    public ulong nTotalPrice;
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nNewClass = reader.ReadByte();
        nTotalPrice = reader.ReadUInt64();
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nNewClass);
        writer.Write(nTotalPrice);
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 40 | Full: 0x0C28
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 40)]
public class PROTO_NC_ITEM_OPENSTORAGEPAGE_REQ : IFiestaPacketBody
{
    public byte page;

    public void Read(BinaryReader reader)
    {
        page = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(page);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 10 | Full: 0x0C0A
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 10)]
public class PROTO_NC_ITEM_PICK_ACK : IFiestaPacketBody
{
    public ushort itemid;
    public uint lot;
    public ushort error;
    public ushort itemhandle;

    public void Read(BinaryReader reader)
    {
        itemid = reader.ReadUInt16();
        lot = reader.ReadUInt32();
        error = reader.ReadUInt16();
        itemhandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemid);
        writer.Write(lot);
        writer.Write(error);
        writer.Write(itemhandle);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 9 | Full: 0x0C09
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 9)]
public class PROTO_NC_ITEM_PICK_REQ : IFiestaPacketBody
{
    public ushort itemhandle;

    public void Read(BinaryReader reader)
    {
        itemhandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemhandle);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 27 | Full: 0x0C1B
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 27)]
public class PROTO_NC_ITEM_PICKOTHER_ACK : IFiestaPacketBody
{
    public ushort itemid;
    public ushort towho;

    public void Read(BinaryReader reader)
    {
        itemid = reader.ReadUInt16();
        towho = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemid);
        writer.Write(towho);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 98 | Full: 0x0C62
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 98)]
public class PROTO_NC_ITEM_RANDOMOPTION_CHANGE_ACCEPT_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 84 | Full: 0x0C54
/// sizeof = 27
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 84)]
public class PROTO_NC_ITEM_RANDOMOPTION_CHANGE_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ItemOptionStorage changeAbleOption = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        changeAbleOption.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        changeAbleOption.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 83 | Full: 0x0C53
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 83)]
public class PROTO_NC_ITEM_RANDOMOPTION_CHANGE_REQ : IFiestaPacketBody
{
    public byte nItemSlotNo;
    public byte nStuffSlotNo;

    public void Read(BinaryReader reader)
    {
        nItemSlotNo = reader.ReadByte();
        nStuffSlotNo = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nItemSlotNo);
        writer.Write(nStuffSlotNo);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 108 | Full: 0x0C6C
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 108)]
public class PROTO_NC_ITEM_RANDOMOPTION_RECOVER_COUNT_LIMIT_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 107 | Full: 0x0C6B
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 107)]
public class PROTO_NC_ITEM_RANDOMOPTION_RECOVER_COUNT_LIMIT_REQ : IFiestaPacketBody
{
    public byte nItemSlotNo;
    public byte nStuffUseLot;

    public void Read(BinaryReader reader)
    {
        nItemSlotNo = reader.ReadByte();
        nStuffUseLot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nItemSlotNo);
        writer.Write(nStuffUseLot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 11 | Full: 0x0C0B
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 11)]
public class PROTO_NC_ITEM_RELOC_REQ : IFiestaPacketBody
{
    public ITEM_INVEN from = new();
    public ITEM_INVEN to = new();

    public void Read(BinaryReader reader)
    {
        from.Read(reader);
        to.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        from.Write(writer);
        to.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 89 | Full: 0x0C59
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 89)]
public class PROTO_NC_ITEM_REPURCHASE_REQ : IFiestaPacketBody
{
    public ushort nHaldle;

    public void Read(BinaryReader reader)
    {
        nHaldle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHaldle);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 45 | Full: 0x0C2D
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 45)]
public class PROTO_NC_ITEM_REWARDINVENOPEN_ACK : IFiestaPacketBody
{
    public byte itemcounter;
    public PROTO_ITEMPACKET_INFORM[] itemarray = [];

    public void Read(BinaryReader reader)
    {
        itemcounter = reader.ReadByte();
        itemarray = new PROTO_ITEMPACKET_INFORM[itemcounter];
        for (int i = 0; i < itemcounter; i++)
        {
            itemarray[i] = new PROTO_ITEMPACKET_INFORM();
            itemarray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemcounter);
        for (int i = 0; i < itemarray.Length; i++)
            itemarray[i].Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 44 | Full: 0x0C2C
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 44)]
public class PROTO_NC_ITEM_REWARDINVENOPEN_REQ : IFiestaPacketBody
{
    public ushort page;

    public void Read(BinaryReader reader)
    {
        page = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(page);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 16 | Full: 0x0C10
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 16)]
public class PROTO_NC_ITEM_RINGEQUIP_REQ : IFiestaPacketBody
{
    public byte slot;
    public byte equip;

    public void Read(BinaryReader reader)
    {
        slot = reader.ReadByte();
        equip = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slot);
        writer.Write(equip);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 93 | Full: 0x0C5D
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 93)]
public class PROTO_NC_ITEM_SELL_ITEM_DELETE_CMD : IFiestaPacketBody
{
    public ushort nHandle;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 92 | Full: 0x0C5C
/// sizeof = 105
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 92)]
public class PROTO_NC_ITEM_SELL_ITEM_INSERT_CMD : IFiestaPacketBody
{
    public ushort nHandle;
    public SHINE_ITEM_STRUCT ItemInfo = new();

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        ItemInfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        ItemInfo.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 91 | Full: 0x0C5B
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 91)]
public class PROTO_NC_ITEM_SELL_ITEM_LIST_CMD : IFiestaPacketBody
{
    public byte NumOfSellItem;
    public PROTO_SELL_ITEM_INFO[] SellItemList = [];

    public void Read(BinaryReader reader)
    {
        NumOfSellItem = reader.ReadByte();
        SellItemList = new PROTO_SELL_ITEM_INFO[NumOfSellItem];
        for (int i = 0; i < NumOfSellItem; i++)
        {
            SellItemList[i] = new PROTO_SELL_ITEM_INFO();
            SellItemList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(NumOfSellItem);
        for (int i = 0; i < SellItemList.Length; i++)
            SellItemList[i].Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 6 | Full: 0x0C06
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 6)]
public class PROTO_NC_ITEM_SELL_REQ : IFiestaPacketBody
{
    public byte slot;
    public uint lot;

    public void Read(BinaryReader reader)
    {
        slot = reader.ReadByte();
        lot = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slot);
        writer.Write(lot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 101 | Full: 0x0C65
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 101)]
public class PROTO_NC_ITEM_SHIELDENDURE_CHARGE_ACK : IFiestaPacketBody
{
    public uint ChargedNumber;
    public ITEM_INVEN ShieldSlot = new();
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        ChargedNumber = reader.ReadUInt32();
        ShieldSlot.Read(reader);
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargedNumber);
        ShieldSlot.Write(writer);
        writer.Write(Error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 100 | Full: 0x0C64
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 100)]
public class PROTO_NC_ITEM_SHIELDENDURE_CHARGE_REQ : IFiestaPacketBody
{
    public byte ChargingSlot;
    public ITEM_INVEN ShieldSlot = new();

    public void Read(BinaryReader reader)
    {
        ChargingSlot = reader.ReadByte();
        ShieldSlot.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargingSlot);
        ShieldSlot.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 102 | Full: 0x0C66
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 102)]
public class PROTO_NC_ITEM_SHIELDENDURESET_CMD : IFiestaPacketBody
{
    public uint ChargedNumber;

    public void Read(BinaryReader reader)
    {
        ChargedNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargedNumber);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 20 | Full: 0x0C14
/// sizeof = 26
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 20)]
public class PROTO_NC_ITEM_SOMEONEPICK_CMD : IFiestaPacketBody
{
    public Name5 pickerID = new();
    public ushort itemID;
    public uint nItemLot;

    public void Read(BinaryReader reader)
    {
        pickerID.Read(reader);
        itemID = reader.ReadUInt16();
        nItemLot = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        pickerID.Write(writer);
        writer.Write(itemID);
        writer.Write(nItemLot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 41 | Full: 0x0C29
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 41)]
public class PROTO_NC_ITEM_SOMEONEUSE_CMD : IFiestaPacketBody
{
    public ushort user;
    public SHINE_XY_TYPE useloc = new();
    public ushort useditem;

    public void Read(BinaryReader reader)
    {
        user = reader.ReadUInt16();
        useloc.Read(reader);
        useditem = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(user);
        useloc.Write(writer);
        writer.Write(useditem);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 13 | Full: 0x0C0D
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 13)]
public class PROTO_NC_ITEM_SPLIT_REQ : IFiestaPacketBody
{
    public ITEM_INVEN from = new();
    public ITEM_INVEN to = new();
    public uint lot;

    public void Read(BinaryReader reader)
    {
        from.Read(reader);
        to.Read(reader);
        lot = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        from.Write(writer);
        to.Write(writer);
        writer.Write(lot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 88 | Full: 0x0C58
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 88)]
public class PROTO_NC_ITEM_TERMEXTEND_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 87 | Full: 0x0C57
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 87)]
public class PROTO_NC_ITEM_TERMEXTEND_REQ : IFiestaPacketBody
{
    public byte nExtendItemSlot;
    public byte nTermItemSlot;

    public void Read(BinaryReader reader)
    {
        nExtendItemSlot = reader.ReadByte();
        nTermItemSlot = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nExtendItemSlot);
        writer.Write(nTermItemSlot);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 18 | Full: 0x0C12
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 18)]
public class PROTO_NC_ITEM_UNEQUIP_REQ : IFiestaPacketBody
{
    public byte slotequip;
    public byte slotinven;

    public void Read(BinaryReader reader)
    {
        slotequip = reader.ReadByte();
        slotinven = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotequip);
        writer.Write(slotinven);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 24 | Full: 0x0C18
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 24)]
public class PROTO_NC_ITEM_UPGRADE_ACK : IFiestaPacketBody
{
    public ushort err;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 23 | Full: 0x0C17
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 23)]
public class PROTO_NC_ITEM_UPGRADE_REQ : IFiestaPacketBody
{
    public byte equip;
    public byte raw;
    public byte raw_left;
    public byte raw_right;
    public uint gift_money;
    public byte raw_middle;

    public void Read(BinaryReader reader)
    {
        equip = reader.ReadByte();
        raw = reader.ReadByte();
        raw_left = reader.ReadByte();
        raw_right = reader.ReadByte();
        gift_money = reader.ReadUInt32();
        raw_middle = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(equip);
        writer.Write(raw);
        writer.Write(raw_left);
        writer.Write(raw_right);
        writer.Write(gift_money);
        writer.Write(raw_middle);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 22 | Full: 0x0C16
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 22)]
public class PROTO_NC_ITEM_USE_ACK : IFiestaPacketBody
{
    public ushort error;
    public ushort useditem;
    public byte invenType;

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
        useditem = reader.ReadUInt16();
        invenType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
        writer.Write(useditem);
        writer.Write(invenType);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 78 | Full: 0x0C4E
/// sizeof = 11
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 78)]
public class PROTO_NC_ITEM_USE_ACTIVESKILL_REQ : IFiestaPacketBody
{
    public byte nInvenSlot;
    public ushort nTargetHnd;
    public SHINE_XY_TYPE TargetLoc = new();

    public void Read(BinaryReader reader)
    {
        nInvenSlot = reader.ReadByte();
        nTargetHnd = reader.ReadUInt16();
        TargetLoc.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nInvenSlot);
        writer.Write(nTargetHnd);
        TargetLoc.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 21 | Full: 0x0C15
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 21)]
public class PROTO_NC_ITEM_USE_REQ : IFiestaPacketBody
{
    public byte invenslot;
    public byte invenType;

    public void Read(BinaryReader reader)
    {
        invenslot = reader.ReadByte();
        invenType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(invenslot);
        writer.Write(invenType);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 54 | Full: 0x0C36
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 54)]
public class PROTO_NC_ITEM_WEAPONENDURE_CHARGE_ACK : IFiestaPacketBody
{
    public uint ChargedNumber;
    public ITEM_INVEN WeaponSlot = new();
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        ChargedNumber = reader.ReadUInt32();
        WeaponSlot.Read(reader);
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargedNumber);
        WeaponSlot.Write(writer);
        writer.Write(Error);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 53 | Full: 0x0C35
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 53)]
public class PROTO_NC_ITEM_WEAPONENDURE_CHARGE_REQ : IFiestaPacketBody
{
    public byte ChargingSlot;
    public ITEM_INVEN WeaponSlot = new();

    public void Read(BinaryReader reader)
    {
        ChargingSlot = reader.ReadByte();
        WeaponSlot.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargingSlot);
        WeaponSlot.Write(writer);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 55 | Full: 0x0C37
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 55)]
public class PROTO_NC_ITEM_WEAPONENDURESET_CMD : IFiestaPacketBody
{
    public uint ChargedNumber;

    public void Read(BinaryReader reader)
    {
        ChargedNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChargedNumber);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 31 | Full: 0x0C1F
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 31)]
public class PROTO_NC_ITEM_WITHDRAW_ACK : IFiestaPacketBody
{
    public ulong cen;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Item (0x0C) | Opcode: 30 | Full: 0x0C1E
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Item, 30)]
public class PROTO_NC_ITEM_WITHDRAW_REQ : IFiestaPacketBody
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }
}

