// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 5</summary>
public class PROTO_NC_KQ_ENTRYRESPONCE_ACK
{
    public byte Reply;
    public uint EncHandle;

    public void Read(BinaryReader reader)
    {
        Reply = reader.ReadByte();
        EncHandle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Reply);
        writer.Write(EncHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_KQ_JOIN_ACK
{
    public uint Handle;
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
        writer.Write(Error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_KQ_JOIN_CANCEL_ACK
{
    public uint Handle;
    public ushort Error;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
        Error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
        writer.Write(Error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_JOIN_CANCEL_REQ
{
    public uint Handle;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_KQ_JOIN_LIST_ACK
{
    public ushort nError;
    public byte nNum;
    public KQ_JOIN_CHAR_INFO[] CharInfoList = [];

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nNum = reader.ReadByte();
        CharInfoList = new KQ_JOIN_CHAR_INFO[nNum];
        for (int i = 0; i < nNum; i++)
        {
            CharInfoList[i] = new KQ_JOIN_CHAR_INFO();
            CharInfoList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nNum);
        for (int i = 0; i < CharInfoList.Length; i++)
            CharInfoList[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_JOIN_LIST_REQ
{
    public uint nHandle;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_JOIN_REQ
{
    public uint Handle;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 5</summary>
public class PROTO_NC_KQ_JOINER
{
    public uint chrregnum;
    public byte nTeamType;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        nTeamType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(nTeamType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_KQ_JOINING_ALARM_CMD
{
    public KQ_JOINING_ALARM_INFO KQInfo = new();
    public byte MsgLength;
    public byte[] Msg = [];

    public void Read(BinaryReader reader)
    {
        KQInfo.Read(reader);
        MsgLength = reader.ReadByte();
        Msg = reader.ReadBytes(MsgLength);
    }

    public void Write(BinaryWriter writer)
    {
        KQInfo.Write(writer);
        writer.Write(MsgLength);
        writer.Write(Msg);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_KQ_JOINING_ALARM_END_CMD
{
    public uint nHandle;
    public ushort nID;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt32();
        nID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nID);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_JOINING_ALARM_LIST
{
    public ushort nNumOfKQ;
    public KQ_JOINING_ALARM_INFO[] KQList = [];

    public void Read(BinaryReader reader)
    {
        nNumOfKQ = reader.ReadUInt16();
        KQList = new KQ_JOINING_ALARM_INFO[nNumOfKQ];
        for (int i = 0; i < nNumOfKQ; i++)
        {
            KQList[i] = new KQ_JOINING_ALARM_INFO();
            KQList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nNumOfKQ);
        for (int i = 0; i < KQList.Length; i++)
            KQList[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 52</summary>
public class PROTO_NC_KQ_LINK_TO_FORCE_BY_BAN_CMD
{
    public uint nCharNum;
    public Name3[] sMapName = new Name3[4];

    public void Read(BinaryReader reader)
    {
        nCharNum = reader.ReadUInt32();
        for (int i = 0; i < 4; i++)
        {
            sMapName[i] = new Name3();
            sMapName[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNum);
        for (int i = 0; i < 4; i++)
            sMapName[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 50</summary>
public class PROTO_NC_KQ_LIST_ACK
{
    public int ServerTime;
    public tm tm_ServerTime = new();
    public uint NewStartHandle;
    public uint NewEndHandle;
    public ushort NumOfNewQuest;
    public PROTO_KQ_INFO_CLIENT[] NewQuestArray = [];

    public void Read(BinaryReader reader)
    {
        ServerTime = reader.ReadInt32();
        tm_ServerTime.Read(reader);
        NewStartHandle = reader.ReadUInt32();
        NewEndHandle = reader.ReadUInt32();
        NumOfNewQuest = reader.ReadUInt16();
        NewQuestArray = new PROTO_KQ_INFO_CLIENT[NumOfNewQuest];
        for (int i = 0; i < NumOfNewQuest; i++)
        {
            NewQuestArray[i] = new PROTO_KQ_INFO_CLIENT();
            NewQuestArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ServerTime);
        tm_ServerTime.Write(writer);
        writer.Write(NewStartHandle);
        writer.Write(NewEndHandle);
        writer.Write(NumOfNewQuest);
        for (int i = 0; i < NewQuestArray.Length; i++)
            NewQuestArray[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_LIST_ADD_ACK
{
    public ushort NumOfAdd;
    public PROTO_KQ_INFO_CLIENT[] AddQuestArray = [];

    public void Read(BinaryReader reader)
    {
        NumOfAdd = reader.ReadUInt16();
        AddQuestArray = new PROTO_KQ_INFO_CLIENT[NumOfAdd];
        for (int i = 0; i < NumOfAdd; i++)
        {
            AddQuestArray[i] = new PROTO_KQ_INFO_CLIENT();
            AddQuestArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(NumOfAdd);
        for (int i = 0; i < AddQuestArray.Length; i++)
            AddQuestArray[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_LIST_DELETE_ACK
{
    public ushort NumOfDelete;
    public uint[] DeleteQuestArray = [];

    public void Read(BinaryReader reader)
    {
        NumOfDelete = reader.ReadUInt16();
        DeleteQuestArray = new uint[NumOfDelete];
        for (int i = 0; i < NumOfDelete; i++)
            DeleteQuestArray[i] = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(NumOfDelete);
        for (int i = 0; i < DeleteQuestArray.Length; i++)
            writer.Write(DeleteQuestArray[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_LIST_REFRESH_REQ
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_KQ_LIST_REQ
{
    public uint StartHandle;
    public uint EndHandle;

    public void Read(BinaryReader reader)
    {
        StartHandle = reader.ReadUInt32();
        EndHandle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(StartHandle);
        writer.Write(EndHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 40</summary>
public class PROTO_NC_KQ_LIST_TIME_ACK
{
    public int ServerTime;
    public tm tm_ServerTime = new();

    public void Read(BinaryReader reader)
    {
        ServerTime = reader.ReadInt32();
        tm_ServerTime.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ServerTime);
        tm_ServerTime.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_LIST_UPDATE_ACK
{
    public ushort NumOfUpdate;
    public KQ_UPDATE_ITEMS[] UpdateQuestArray = [];

    public void Read(BinaryReader reader)
    {
        NumOfUpdate = reader.ReadUInt16();
        UpdateQuestArray = new KQ_UPDATE_ITEMS[NumOfUpdate];
        for (int i = 0; i < NumOfUpdate; i++)
        {
            UpdateQuestArray[i] = new KQ_UPDATE_ITEMS();
            UpdateQuestArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(NumOfUpdate);
        for (int i = 0; i < UpdateQuestArray.Length; i++)
            UpdateQuestArray[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_MOBKILLNUMBER_CMD
{
    public ushort CurrentMobKill;
    public ushort DemandMobKill;

    public void Read(BinaryReader reader)
    {
        CurrentMobKill = reader.ReadUInt16();
        DemandMobKill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CurrentMobKill);
        writer.Write(DemandMobKill);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_NOTIFY_CMD
{
    public byte MsgLength;
    public byte[] Msg = [];

    public void Read(BinaryReader reader)
    {
        MsgLength = reader.ReadByte();
        Msg = reader.ReadBytes(MsgLength);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(MsgLength);
        writer.Write(Msg);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_KQ_PLAYER_DISJOIN_CMD
{
    public uint nHandle;
    public uint nCharNum;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt32();
        nCharNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nCharNum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_RESTDEADNUM_CMD
{
    public byte number;

    public void Read(BinaryReader reader)
    {
        number = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(number);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 35</summary>
public class PROTO_NC_KQ_REWARD_REQ
{
    public uint fame;
    public ulong cen;
    public PROTO_NC_ITEMDB_CREATEITEMLIST_REQ itmlst = new();

    public void Read(BinaryReader reader)
    {
        fame = reader.ReadUInt32();
        cen = reader.ReadUInt64();
        itmlst.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(fame);
        writer.Write(cen);
        itmlst.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_KQ_REWARDFAIL_ACK
{
    public NETPACKETZONEHEADER header = new();
    public ushort lockindex;
    public ushort error;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        lockindex = reader.ReadUInt16();
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(lockindex);
        writer.Write(error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_KQ_REWARDSUC_ACK
{
    public NETPACKETZONEHEADER header = new();
    public ushort lockindex;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        lockindex = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(lockindex);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_KQ_SCHEDULE_ACK
{
    public uint NewStartHandle;
    public uint NewEndHandle;
    public ushort NumOfNewQuest;
    public PROTO_KQ_INFO_CLIENT[] NewQuestArray = [];

    public void Read(BinaryReader reader)
    {
        NewStartHandle = reader.ReadUInt32();
        NewEndHandle = reader.ReadUInt32();
        NumOfNewQuest = reader.ReadUInt16();
        NewQuestArray = new PROTO_KQ_INFO_CLIENT[NumOfNewQuest];
        for (int i = 0; i < NumOfNewQuest; i++)
        {
            NewQuestArray[i] = new PROTO_KQ_INFO_CLIENT();
            NewQuestArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(NewStartHandle);
        writer.Write(NewEndHandle);
        writer.Write(NumOfNewQuest);
        for (int i = 0; i < NewQuestArray.Length; i++)
            NewQuestArray[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_KQ_SCHEDULE_REQ
{
    public uint StartHandle;
    public uint EndHandle;

    public void Read(BinaryReader reader)
    {
        StartHandle = reader.ReadUInt32();
        EndHandle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(StartHandle);
        writer.Write(EndHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_KQ_SCORE_BOARD_INFO_CMD
{
    public byte bUseRound;
    public byte nRound;
    public TEAM_SCORE_INFO Red = new();
    public TEAM_SCORE_INFO Blue = new();

    public void Read(BinaryReader reader)
    {
        bUseRound = reader.ReadByte();
        nRound = reader.ReadByte();
        Red.Read(reader);
        Blue.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(bUseRound);
        writer.Write(nRound);
        Red.Write(writer);
        Blue.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 5</summary>
public class PROTO_NC_KQ_SCORE_CMD
{
    public byte num;
    public uint @base;
    // PROTO_NC_KQ_SCORE_CMD::KQScore[0] array at offset 5 (unsupported type)

    public void Read(BinaryReader reader)
    {
        num = reader.ReadByte();
        @base = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(num);
        writer.Write(@base);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_KQ_SCORE_INFO_CMD
{
    public uint[] nScore = new uint[2];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 2; i++)
            nScore[i] = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 2; i++)
            writer.Write(nScore[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 18</summary>
public class PROTO_NC_KQ_SCORE_SIMPLE_CMD
{
    public byte num;
    public uint @base;
    // PROTO_NC_KQ_SCORE_SIMPLE_CMD::<unnamed-type-self> self at offset 5 (unsupported type)
    // PROTO_NC_KQ_SCORE_SIMPLE_CMD::KQScore[0] array at offset 18 (unsupported type)

    public void Read(BinaryReader reader)
    {
        num = reader.ReadByte();
        @base = reader.ReadUInt32();
        reader.ReadBytes(13); // skip PROTO_NC_KQ_SCORE_SIMPLE_CMD::<unnamed-type-self> self
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(num);
        writer.Write(@base);
        writer.Write(new byte[13]); // skip PROTO_NC_KQ_SCORE_SIMPLE_CMD::<unnamed-type-self> self
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 7</summary>
public class PROTO_NC_KQ_STATUS_ACK
{
    public uint Handle;
    public byte Status;
    public ushort NumOfJoiner;
    public Name5[] JoinerNameList = [];

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
        Status = reader.ReadByte();
        NumOfJoiner = reader.ReadUInt16();
        JoinerNameList = new Name5[NumOfJoiner];
        for (int i = 0; i < NumOfJoiner; i++)
        {
            JoinerNameList[i] = new Name5();
            JoinerNameList[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
        writer.Write(Status);
        writer.Write(NumOfJoiner);
        for (int i = 0; i < JoinerNameList.Length; i++)
            JoinerNameList[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_STATUS_REQ
{
    public uint Handle;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_KQ_TEAM_SELECT_ACK
{
    public ushort nError;
    public byte nTeamType;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nTeamType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nTeamType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 21</summary>
public class PROTO_NC_KQ_TEAM_SELECT_CMD
{
    public Name5 sCharID = new();
    public byte nTeamType;

    public void Read(BinaryReader reader)
    {
        sCharID.Read(reader);
        nTeamType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        sCharID.Write(writer);
        writer.Write(nTeamType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_TEAM_SELECT_REQ
{
    public byte nTeamType;

    public void Read(BinaryReader reader)
    {
        nTeamType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nTeamType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_TEAM_TYPE_CMD
{
    public byte nTeamType;

    public void Read(BinaryReader reader)
    {
        nTeamType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nTeamType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_VOTE_BAN_MSG_CMD
{
    public byte nVoteRate;
    public byte nYesNum;
    public byte nNoNum;
    public byte nCancelNum;

    public void Read(BinaryReader reader)
    {
        nVoteRate = reader.ReadByte();
        nYesNum = reader.ReadByte();
        nNoNum = reader.ReadByte();
        nCancelNum = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nVoteRate);
        writer.Write(nYesNum);
        writer.Write(nNoNum);
        writer.Write(nCancelNum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_VOTE_BAN_MSG_LOGOFF_CMD
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 20</summary>
public class PROTO_NC_KQ_VOTE_CANCEL_CMD
{
    public Name5 sTarget = new();

    public void Read(BinaryReader reader)
    {
        sTarget.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        sTarget.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 23</summary>
public class PROTO_NC_KQ_VOTE_RESULT_FAIL_CMD
{
    public Name5 sTarget = new();
    public byte nYesNum;
    public byte nNoNum;
    public byte nCancelNum;

    public void Read(BinaryReader reader)
    {
        sTarget.Read(reader);
        nYesNum = reader.ReadByte();
        nNoNum = reader.ReadByte();
        nCancelNum = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        sTarget.Write(writer);
        writer.Write(nYesNum);
        writer.Write(nNoNum);
        writer.Write(nCancelNum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 24</summary>
public class PROTO_NC_KQ_VOTE_RESULT_SUC_CMD
{
    public Name5 sTarget = new();
    public byte nVoteRate;
    public byte nYesNum;
    public byte nNoNum;
    public byte nCancelNum;

    public void Read(BinaryReader reader)
    {
        sTarget.Read(reader);
        nVoteRate = reader.ReadByte();
        nYesNum = reader.ReadByte();
        nNoNum = reader.ReadByte();
        nCancelNum = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        sTarget.Write(writer);
        writer.Write(nVoteRate);
        writer.Write(nYesNum);
        writer.Write(nNoNum);
        writer.Write(nCancelNum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_VOTE_START_ACK
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_VOTE_START_CHECK_ACK
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_KQ_VOTE_START_CHECK_REQ
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 22</summary>
public class PROTO_NC_KQ_VOTE_START_REQ
{
    public Name5 sTarget = new();
    public byte nVoteType;
    public byte nLen;
    public byte[] sContents = [];

    public void Read(BinaryReader reader)
    {
        sTarget.Read(reader);
        nVoteType = reader.ReadByte();
        nLen = reader.ReadByte();
        sContents = reader.ReadBytes(nLen);
    }

    public void Write(BinaryWriter writer)
    {
        sTarget.Write(writer);
        writer.Write(nVoteType);
        writer.Write(nLen);
        writer.Write(sContents);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_KQ_VOTE_VOTING_ACK
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 78</summary>
public class PROTO_NC_KQ_VOTE_VOTING_CMD
{
    public Name5 sStarter = new();
    public Name5 sTarget = new();
    public byte nVoteType;
    public tm tEndTime = new();
    public byte nLen;
    public byte[] sContents = [];

    public void Read(BinaryReader reader)
    {
        sStarter.Read(reader);
        sTarget.Read(reader);
        nVoteType = reader.ReadByte();
        tEndTime.Read(reader);
        nLen = reader.ReadByte();
        sContents = reader.ReadBytes(nLen);
    }

    public void Write(BinaryWriter writer)
    {
        sStarter.Write(writer);
        sTarget.Write(writer);
        writer.Write(nVoteType);
        tEndTime.Write(writer);
        writer.Write(nLen);
        writer.Write(sContents);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_VOTE_VOTING_REQ
{
    // KQ_VOTING_TYPE eVoteType at offset 0 (unsupported type)

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_W2Z_DESTROY_CMD
{
    public uint hquest;

    public void Read(BinaryReader reader)
    {
        hquest = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hquest);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 377</summary>
public class PROTO_NC_KQ_W2Z_MAKE_REQ
{
    public PROTO_KQ_INFO KQInfo = new();

    public void Read(BinaryReader reader)
    {
        KQInfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        KQInfo.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 379</summary>
public class PROTO_NC_KQ_W2Z_START_CMD
{
    public PROTO_KQ_INFO KQInfo = new();
    public ushort NumOfJoiner;
    public PROTO_NC_KQ_JOINER[] JoinerArray = [];

    public void Read(BinaryReader reader)
    {
        KQInfo.Read(reader);
        NumOfJoiner = reader.ReadUInt16();
        JoinerArray = new PROTO_NC_KQ_JOINER[NumOfJoiner];
        for (int i = 0; i < NumOfJoiner; i++)
        {
            JoinerArray[i] = new PROTO_NC_KQ_JOINER();
            JoinerArray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        KQInfo.Write(writer);
        writer.Write(NumOfJoiner);
        for (int i = 0; i < JoinerArray.Length; i++)
            JoinerArray[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_WINTER_EVENT_2014_SCORE_CMD
{
    public TEAM_SCORE_INFO Red = new();
    public TEAM_SCORE_INFO Blue = new();

    public void Read(BinaryReader reader)
    {
        Red.Read(reader);
        Blue.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        Red.Write(writer);
        Blue.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_KQ_Z2W_END_CMD
{
    public uint Handle;

    public void Read(BinaryReader reader)
    {
        Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(Handle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_KQ_Z2W_MAKE_ACK
{
    public uint hquest;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        hquest = reader.ReadUInt32();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hquest);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

