// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 4</summary>
public class PROTO_NC_LOG_GAME_CREATE_AVATAR
{
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 7</summary>
public class PROTO_NC_LOG_GAME_CREATE_AVATAR_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_GAME_CREATE_AVATAR log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 68</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_0
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
        writer.Write(nBigint1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_1
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 40</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_2
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 44</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_3
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public uint nInt1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nInt1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 44</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_4
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 16</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_5
{
    public uint nType;
    public uint nCharNo;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 44</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_6
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nBigint1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 44</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_7
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 36</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_8
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 48</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_9
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 36</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_A
{
    public uint nType;
    public uint nCharNo;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 60</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_B
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 56</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_C
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 24</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_D
{
    public uint nType;
    public uint nCharNo;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 48</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_E
{
    public uint nType;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 64</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_F
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
        writer.Write(nBigint1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 60</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_G
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nBigint1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 36</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_H
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 40</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_I
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 52</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_J
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 48</summary>
public class PROTO_NC_LOG_GAME_DATA_TYPE_K
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nBigint1);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_LOG_GAME_DELETE_AVATAR
{
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 7</summary>
public class PROTO_NC_LOG_GAME_DELETE_AVATAR_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_GAME_DELETE_AVATAR log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_LOG_GAME_ITEM_CW_BREAKATZERO
{
    public uint chrregnum;
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        itemkey.Read(reader);
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        itemkey.Write(writer);
        mappos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 16</summary>
public class PROTO_NC_LOG_GAME_ITEM_PUT_ON_BELONGED
{
    public uint chrregnum;
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public ITEM_INVEN iteminvenfrom = new();
    public ITEM_INVEN iteminvento = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        itemkey.Read(reader);
        iteminvenfrom.Read(reader);
        iteminvento.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        itemkey.Write(writer);
        iteminvenfrom.Write(writer);
        iteminvento.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 43</summary>
public class PROTO_NC_LOG_GAME_ITEM_UPGRADE
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public byte itemoldlevel;
    public byte itemnewlevel;
    public ushort left_item_id;
    public ushort right_item_id;
    public ushort middle_item_id;
    // ItemOptionStorage::Element randomoption_elemental at offset 40 (unsupported type)

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        itemkey.Read(reader);
        itemoldlevel = reader.ReadByte();
        itemnewlevel = reader.ReadByte();
        left_item_id = reader.ReadUInt16();
        right_item_id = reader.ReadUInt16();
        middle_item_id = reader.ReadUInt16();
        reader.ReadBytes(3); // skip ItemOptionStorage::Element randomoption_elemental
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        itemkey.Write(writer);
        writer.Write(itemoldlevel);
        writer.Write(itemnewlevel);
        writer.Write(left_item_id);
        writer.Write(right_item_id);
        writer.Write(middle_item_id);
        writer.Write(new byte[3]); // skip ItemOptionStorage::Element randomoption_elemental
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 30</summary>
public class PROTO_NC_LOG_GAME_KQ_ENTER
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort KQ_ID;
    public uint KQ_Handle;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        KQ_ID = reader.ReadUInt16();
        KQ_Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(KQ_ID);
        writer.Write(KQ_Handle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 31</summary>
public class PROTO_NC_LOG_GAME_KQ_LEAVE
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort KQ_ID;
    public uint KQ_Handle;
    public byte Leave_Status;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        KQ_ID = reader.ReadUInt16();
        KQ_Handle = reader.ReadUInt32();
        Leave_Status = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(KQ_ID);
        writer.Write(KQ_Handle);
        writer.Write(Leave_Status);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 33</summary>
public class PROTO_NC_LOG_GAME_LEVEL_UP
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte level;
    public ulong currentexp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        level = reader.ReadByte();
        currentexp = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(level);
        writer.Write(currentexp);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 41</summary>
public class PROTO_NC_LOG_GAME_LINK
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte StoreType;
    public ulong CharExp;
    public ulong CharMoney;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        StoreType = reader.ReadByte();
        CharExp = reader.ReadUInt64();
        CharMoney = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(StoreType);
        writer.Write(CharExp);
        writer.Write(CharMoney);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 24</summary>
public class PROTO_NC_LOG_GAME_MINIHOUSE_BUILDING
{
    public uint chrregnum;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 28</summary>
public class PROTO_NC_LOG_GAME_MINIHOUSE_VISIT
{
    public uint owner_chrregnum;
    public uint visitor_chrregnum;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        owner_chrregnum = reader.ReadUInt32();
        visitor_chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(owner_chrregnum);
        writer.Write(visitor_chrregnum);
        mappos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_LOG_GAME_MK_DROP_ITEM
{
    public ushort nItemID;
    public ushort nLot;
    public SHINE_ITEM_REGISTNUMBER nItemKey = new();
    public ushort mobid;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        nItemID = reader.ReadUInt16();
        nLot = reader.ReadUInt16();
        nItemKey.Read(reader);
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nItemID);
        writer.Write(nLot);
        nItemKey.Write(writer);
        writer.Write(mobid);
        mappos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_LOG_GAME_MK_GETEXPINFIELD
{
    public uint chrregnum;
    public ushort mobid;
    public ushort number;
    public uint exp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mobid = reader.ReadUInt16();
        number = reader.ReadUInt16();
        exp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(mobid);
        writer.Write(number);
        writer.Write(exp);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 26</summary>
public class PROTO_NC_LOG_GAME_MK2_DEAD
{
    public ushort mobid;
    public MAPPOS mappos = new();
    public uint nCharNo;

    public void Read(BinaryReader reader)
    {
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
        nCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mobid);
        mappos.Write(writer);
        writer.Write(nCharNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 28</summary>
public class PROTO_NC_LOG_GAME_MK2_START
{
    public uint chrregnum;
    public byte nLevel;
    public byte nClass;
    public ushort mobid;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        nLevel = reader.ReadByte();
        nClass = reader.ReadByte();
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(nLevel);
        writer.Write(nClass);
        writer.Write(mobid);
        mappos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_LOG_GAME_MKED
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort mobid;
    public ulong exp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        mobid = reader.ReadUInt16();
        exp = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(mobid);
        writer.Write(exp);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 33</summary>
public class PROTO_NC_LOG_GAME_PKED
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public uint killerdiechrrgnum;
    public uint pkcount;
    public byte pkyellowtime;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        killerdiechrrgnum = reader.ReadUInt32();
        pkcount = reader.ReadUInt32();
        pkyellowtime = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(killerdiechrrgnum);
        writer.Write(pkcount);
        writer.Write(pkyellowtime);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 41</summary>
public class PROTO_NC_LOG_GMAE_LOGOUT_ZONEINFO
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte StoreType;
    public ulong CharExp;
    public ulong CharMoney;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        StoreType = reader.ReadByte();
        CharExp = reader.ReadUInt64();
        CharMoney = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(StoreType);
        writer.Write(CharExp);
        writer.Write(CharMoney);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 38</summary>
public class PROTO_NC_LOG_REGENLOCATESAVE_CMD
{
    public uint ChrRegNum;
    public Name3 SaveMap = new();
    public SHINE_XY_TYPE SaveLocate = new();
    public uint KQHandle;
    public SHINE_XY_TYPE InvalidLocate = new();
    public ushort Flag;

    public void Read(BinaryReader reader)
    {
        ChrRegNum = reader.ReadUInt32();
        SaveMap.Read(reader);
        SaveLocate.Read(reader);
        KQHandle = reader.ReadUInt32();
        InvalidLocate.Read(reader);
        Flag = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChrRegNum);
        SaveMap.Write(writer);
        SaveLocate.Write(writer);
        writer.Write(KQHandle);
        InvalidLocate.Write(writer);
        writer.Write(Flag);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_LOG_USER_LOGIN
{
    public uint usrregnum;
    public byte worldnum;
    public byte[] ip = new byte[4];

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        ip = reader.ReadBytes(4);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(ip, 0, 4);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_LOG_USER_LOGIN_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGIN log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 278</summary>
public class PROTO_NC_LOG_USER_LOGINFAIL
{
    public Name256Byte userid = new();
    public Name4 userpassword = new();
    public byte[] userip = new byte[4];
    public ushort error;

    public void Read(BinaryReader reader)
    {
        userid.Read(reader);
        userpassword.Read(reader);
        userip = reader.ReadBytes(4);
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        userid.Write(writer);
        userpassword.Write(writer);
        writer.Write(userip, 0, 4);
        writer.Write(error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 281</summary>
public class PROTO_NC_LOG_USER_LOGINFAIL_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGINFAIL log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_LOG_USER_LOGOUT
{
    public uint usrregnum;
    public byte worldnum;
    public ushort playmin;
    public ushort error;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        playmin = reader.ReadUInt16();
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(playmin);
        writer.Write(error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_LOG_USER_LOGOUT_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGOUT log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_LOG_WEDDING_HALL_CANCEL
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_LOG_WEDDING_HALL_RESERVE
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_LOG_WEDDING_HALL_START
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

