// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Log (0x01) | Opcode: 17 | Full: 0x0111
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 17)]
public class PROTO_NC_LOG_GAME_CREATE_AVATAR : IFiestaPacketBody
{
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
    }
}

/// <summary>sizeof = 7</summary>
public class PROTO_NC_LOG_GAME_CREATE_AVATAR_SEND : IFiestaPacketBody
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_GAME_CREATE_AVATAR log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1000 | Full: 0x03E8
/// sizeof = 68
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1000)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_0 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
        writer.Write(nBigint1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1001 | Full: 0x03E9
/// sizeof = 32
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1001)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_1 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1002 | Full: 0x03EA
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1002)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_2 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1003 | Full: 0x03EB
/// sizeof = 44
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1003)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_3 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public uint nInt1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nInt1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1004 | Full: 0x03EC
/// sizeof = 44
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1004)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_4 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1005 | Full: 0x03ED
/// sizeof = 16
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1005)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_5 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1006 | Full: 0x03EE
/// sizeof = 44
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1006)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_6 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nBigint1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1007 | Full: 0x03EF
/// sizeof = 44
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1007)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_7 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1008 | Full: 0x03F0
/// sizeof = 36
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1008)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_8 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1009 | Full: 0x03F1
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1009)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_9 : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1010 | Full: 0x03F2
/// sizeof = 36
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1010)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_A : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1011 | Full: 0x03F3
/// sizeof = 60
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1011)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_B : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1012 | Full: 0x03F4
/// sizeof = 56
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1012)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_C : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1013 | Full: 0x03F5
/// sizeof = 24
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1013)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_D : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1014 | Full: 0x03F6
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1014)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_E : IFiestaPacketBody
{
    public uint nType;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1015 | Full: 0x03F7
/// sizeof = 64
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1015)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_F : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public uint nInt3;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nInt3 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nInt3);
        writer.Write(nBigint1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1016 | Full: 0x03F8
/// sizeof = 60
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1016)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_G : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nBigint1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1017 | Full: 0x03F9
/// sizeof = 36
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1017)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_H : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1018 | Full: 0x03FA
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1018)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_I : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetCharNo;
    public uint nTargetID;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetCharNo = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetCharNo);
        writer.Write(nTargetID);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1019 | Full: 0x03FB
/// sizeof = 52
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1019)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_J : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nTargetID;
    public ulong nItemKey;
    public uint nInt1;
    public uint nInt2;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nTargetID = reader.ReadUInt32();
        nItemKey = reader.ReadUInt64();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nTargetID);
        writer.Write(nItemKey);
        writer.Write(nInt1);
        writer.Write(nInt2);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 1020 | Full: 0x03FC
/// sizeof = 48
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 1020)]
public class PROTO_NC_LOG_GAME_DATA_TYPE_K : IFiestaPacketBody
{
    public uint nType;
    public uint nCharNo;
    public Name3 sMap = new();
    public uint nMapX;
    public uint nMapY;
    public uint nMapZ;
    public uint nInt1;
    public uint nInt2;
    public ulong nBigint1;

    public void Read(BinaryReader reader)
    {
        nType = reader.ReadUInt32();
        nCharNo = reader.ReadUInt32();
        sMap.Read(reader);
        nMapX = reader.ReadUInt32();
        nMapY = reader.ReadUInt32();
        nMapZ = reader.ReadUInt32();
        nInt1 = reader.ReadUInt32();
        nInt2 = reader.ReadUInt32();
        nBigint1 = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nType);
        writer.Write(nCharNo);
        sMap.Write(writer);
        writer.Write(nMapX);
        writer.Write(nMapY);
        writer.Write(nMapZ);
        writer.Write(nInt1);
        writer.Write(nInt2);
        writer.Write(nBigint1);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 18 | Full: 0x0112
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 18)]
public class PROTO_NC_LOG_GAME_DELETE_AVATAR : IFiestaPacketBody
{
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
    }
}

/// <summary>sizeof = 7</summary>
public class PROTO_NC_LOG_GAME_DELETE_AVATAR_SEND : IFiestaPacketBody
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_GAME_DELETE_AVATAR log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 530 | Full: 0x0312
/// sizeof = 32
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 530)]
public class PROTO_NC_LOG_GAME_ITEM_CW_BREAKATZERO : IFiestaPacketBody
{
    public uint chrregnum;
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        itemkey.Read(reader);
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        itemkey.Write(writer);
        mappos.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 340 | Full: 0x0154
/// sizeof = 16
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 340)]
public class PROTO_NC_LOG_GAME_ITEM_PUT_ON_BELONGED : IFiestaPacketBody
{
    public uint chrregnum;
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public ITEM_INVEN iteminvenfrom = new();
    public ITEM_INVEN iteminvento = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        itemkey.Read(reader);
        iteminvenfrom.Read(reader);
        iteminvento.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        itemkey.Write(writer);
        iteminvenfrom.Write(writer);
        iteminvento.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 82 | Full: 0x0152
/// sizeof = 43
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 82)]
public class PROTO_NC_LOG_GAME_ITEM_UPGRADE : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public SHINE_ITEM_REGISTNUMBER itemkey = new();
    public byte itemoldlevel;
    public byte itemnewlevel;
    public ushort left_item_id;
    public ushort right_item_id;
    public ushort middle_item_id;
    // ItemOptionStorage::Element randomoption_elemental at offset 40 (unsupported type)

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        itemkey.Read(reader);
        itemoldlevel = reader.ReadByte();
        itemnewlevel = reader.ReadByte();
        left_item_id = reader.ReadUInt16();
        right_item_id = reader.ReadUInt16();
        middle_item_id = reader.ReadUInt16();
        reader.ReadBytes(3); // skip ItemOptionStorage::Element randomoption_elemental
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        itemkey.Write(writer);
        writer.Write(itemoldlevel);
        writer.Write(itemnewlevel);
        writer.Write(left_item_id);
        writer.Write(right_item_id);
        writer.Write(middle_item_id);
        writer.Write(new byte[3]); // skip ItemOptionStorage::Element randomoption_elemental
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 65 | Full: 0x0141
/// sizeof = 30
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 65)]
public class PROTO_NC_LOG_GAME_KQ_ENTER : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort KQ_ID;
    public uint KQ_Handle;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        KQ_ID = reader.ReadUInt16();
        KQ_Handle = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(KQ_ID);
        writer.Write(KQ_Handle);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 66 | Full: 0x0142
/// sizeof = 31
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 66)]
public class PROTO_NC_LOG_GAME_KQ_LEAVE : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort KQ_ID;
    public uint KQ_Handle;
    public byte Leave_Status;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        KQ_ID = reader.ReadUInt16();
        KQ_Handle = reader.ReadUInt32();
        Leave_Status = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(KQ_ID);
        writer.Write(KQ_Handle);
        writer.Write(Leave_Status);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 30 | Full: 0x011E
/// sizeof = 33
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 30)]
public class PROTO_NC_LOG_GAME_LEVEL_UP : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte level;
    public ulong currentexp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        level = reader.ReadByte();
        currentexp = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(level);
        writer.Write(currentexp);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 15 | Full: 0x010F
/// sizeof = 41
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 15)]
public class PROTO_NC_LOG_GAME_LINK : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte StoreType;
    public ulong CharExp;
    public ulong CharMoney;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        StoreType = reader.ReadByte();
        CharExp = reader.ReadUInt64();
        CharMoney = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(StoreType);
        writer.Write(CharExp);
        writer.Write(CharMoney);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 201 | Full: 0x01C9
/// sizeof = 24
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 201)]
public class PROTO_NC_LOG_GAME_MINIHOUSE_BUILDING : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 202 | Full: 0x01CA
/// sizeof = 28
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 202)]
public class PROTO_NC_LOG_GAME_MINIHOUSE_VISIT : IFiestaPacketBody
{
    public uint owner_chrregnum;
    public uint visitor_chrregnum;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        owner_chrregnum = reader.ReadUInt32();
        visitor_chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(owner_chrregnum);
        writer.Write(visitor_chrregnum);
        mappos.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 920 | Full: 0x0398
/// sizeof = 34
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 920)]
public class PROTO_NC_LOG_GAME_MK_DROP_ITEM : IFiestaPacketBody
{
    public ushort nItemID;
    public ushort nLot;
    public SHINE_ITEM_REGISTNUMBER nItemKey = new();
    public ushort mobid;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        nItemID = reader.ReadUInt16();
        nLot = reader.ReadUInt16();
        nItemKey.Read(reader);
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nItemID);
        writer.Write(nLot);
        nItemKey.Write(writer);
        writer.Write(mobid);
        mappos.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 45 | Full: 0x012D
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 45)]
public class PROTO_NC_LOG_GAME_MK_GETEXPINFIELD : IFiestaPacketBody
{
    public uint chrregnum;
    public ushort mobid;
    public ushort number;
    public uint exp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mobid = reader.ReadUInt16();
        number = reader.ReadUInt16();
        exp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(mobid);
        writer.Write(number);
        writer.Write(exp);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 913 | Full: 0x0391
/// sizeof = 26
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 913)]
public class PROTO_NC_LOG_GAME_MK2_DEAD : IFiestaPacketBody
{
    public ushort mobid;
    public MAPPOS mappos = new();
    public uint nCharNo;

    public void Read(BinaryReader reader)
    {
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
        nCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mobid);
        mappos.Write(writer);
        writer.Write(nCharNo);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 910 | Full: 0x038E
/// sizeof = 28
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 910)]
public class PROTO_NC_LOG_GAME_MK2_START : IFiestaPacketBody
{
    public uint chrregnum;
    public byte nLevel;
    public byte nClass;
    public ushort mobid;
    public MAPPOS mappos = new();

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        nLevel = reader.ReadByte();
        nClass = reader.ReadByte();
        mobid = reader.ReadUInt16();
        mappos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(nLevel);
        writer.Write(nClass);
        writer.Write(mobid);
        mappos.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 43 | Full: 0x012B
/// sizeof = 34
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 43)]
public class PROTO_NC_LOG_GAME_MKED : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public ushort mobid;
    public ulong exp;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        mobid = reader.ReadUInt16();
        exp = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(mobid);
        writer.Write(exp);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 41 | Full: 0x0129
/// sizeof = 33
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 41)]
public class PROTO_NC_LOG_GAME_PKED : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public uint killerdiechrrgnum;
    public uint pkcount;
    public byte pkyellowtime;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        killerdiechrrgnum = reader.ReadUInt32();
        pkcount = reader.ReadUInt32();
        pkyellowtime = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(killerdiechrrgnum);
        writer.Write(pkcount);
        writer.Write(pkyellowtime);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 16 | Full: 0x0110
/// sizeof = 41
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 16)]
public class PROTO_NC_LOG_GMAE_LOGOUT_ZONEINFO : IFiestaPacketBody
{
    public uint chrregnum;
    public MAPPOS mappos = new();
    public byte StoreType;
    public ulong CharExp;
    public ulong CharMoney;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        mappos.Read(reader);
        StoreType = reader.ReadByte();
        CharExp = reader.ReadUInt64();
        CharMoney = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        mappos.Write(writer);
        writer.Write(StoreType);
        writer.Write(CharExp);
        writer.Write(CharMoney);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 490 | Full: 0x01EA
/// sizeof = 38
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 490)]
public class PROTO_NC_LOG_REGENLOCATESAVE_CMD : IFiestaPacketBody
{
    public uint ChrRegNum;
    public Name3 SaveMap = new();
    public SHINE_XY_TYPE SaveLocate = new();
    public uint KQHandle;
    public SHINE_XY_TYPE InvalidLocate = new();
    public ushort Flag;

    public void Read(BinaryReader reader)
    {
        ChrRegNum = reader.ReadUInt32();
        SaveMap.Read(reader);
        SaveLocate.Read(reader);
        KQHandle = reader.ReadUInt32();
        InvalidLocate.Read(reader);
        Flag = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(ChrRegNum);
        SaveMap.Write(writer);
        SaveLocate.Write(writer);
        writer.Write(KQHandle);
        InvalidLocate.Write(writer);
        writer.Write(Flag);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 801 | Full: 0x0321
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 801)]
public class PROTO_NC_LOG_USER_LOGIN : IFiestaPacketBody
{
    public uint usrregnum;
    public byte worldnum;
    public byte[] ip = new byte[4];

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        ip = reader.ReadBytes(4);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(ip, 0, 4);
    }
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_LOG_USER_LOGIN_SEND : IFiestaPacketBody
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGIN log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 800 | Full: 0x0320
/// sizeof = 278
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 800)]
public class PROTO_NC_LOG_USER_LOGINFAIL : IFiestaPacketBody
{
    public Name256Byte userid = new();
    public Name4 userpassword = new();
    public byte[] userip = new byte[4];
    public ushort error;

    public void Read(BinaryReader reader)
    {
        userid.Read(reader);
        userpassword.Read(reader);
        userip = reader.ReadBytes(4);
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        userid.Write(writer);
        userpassword.Write(writer);
        writer.Write(userip, 0, 4);
        writer.Write(error);
    }
}

/// <summary>sizeof = 281</summary>
public class PROTO_NC_LOG_USER_LOGINFAIL_SEND : IFiestaPacketBody
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGINFAIL log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 802 | Full: 0x0322
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 802)]
public class PROTO_NC_LOG_USER_LOGOUT : IFiestaPacketBody
{
    public uint usrregnum;
    public byte worldnum;
    public ushort playmin;
    public ushort error;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        playmin = reader.ReadUInt16();
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(playmin);
        writer.Write(error);
    }
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_LOG_USER_LOGOUT_SEND : IFiestaPacketBody
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_LOG_USER_LOGOUT log = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        log.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        log.Write(writer);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 607 | Full: 0x035F
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 607)]
public class PROTO_NC_LOG_WEDDING_HALL_CANCEL : IFiestaPacketBody
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 605 | Full: 0x035D
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 605)]
public class PROTO_NC_LOG_WEDDING_HALL_RESERVE : IFiestaPacketBody
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }
}

/// <summary>
/// Department: Log (0x01) | Opcode: 606 | Full: 0x035E
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Log, 606)]
public class PROTO_NC_LOG_WEDDING_HALL_START : IFiestaPacketBody
{
    public uint CharRegisterNumber;
    public uint PartnerRegisterNumber;

    public void Read(BinaryReader reader)
    {
        CharRegisterNumber = reader.ReadUInt32();
        PartnerRegisterNumber = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CharRegisterNumber);
        writer.Write(PartnerRegisterNumber);
    }
}

