// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Menu (0x0F) | Opcode: 8 | Full: 0x3C08
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Menu, 8)]
public class PROTO_NC_MENU_OPENSTORAGE_CMD : IFiestaPacketBody
{
    public ulong cen;
    public byte maxpage;
    public byte curpage;
    public byte nOpenType;
    public byte itemcounter;
    public PROTO_ITEMPACKET_INFORM[] itemarray = [];

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
        maxpage = reader.ReadByte();
        curpage = reader.ReadByte();
        nOpenType = reader.ReadByte();
        itemcounter = reader.ReadByte();
        itemarray = new PROTO_ITEMPACKET_INFORM[itemcounter];
        for (int i = 0; i < itemcounter; i++)
        {
            itemarray[i] = new PROTO_ITEMPACKET_INFORM();
            itemarray[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
        writer.Write(maxpage);
        writer.Write(curpage);
        writer.Write(nOpenType);
        writer.Write(itemcounter);
        for (int i = 0; i < itemarray.Length; i++)
            itemarray[i].Write(writer);
    }
}

/// <summary>
/// Department: Menu (0x0F) | Opcode: 2 | Full: 0x3C02
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Menu, 2)]
public class PROTO_NC_MENU_SERVERMENU_ACK : IFiestaPacketBody
{
    public byte reply;

    public void Read(BinaryReader reader)
    {
        reply = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(reply);
    }
}

/// <summary>
/// Department: Menu (0x0F) | Opcode: 1 | Full: 0x3C01
/// sizeof = 142
/// </summary>
[FiestaOpcode(ProtocolCommand.Menu, 1)]
public class PROTO_NC_MENU_SERVERMENU_REQ : IFiestaPacketBody
{
    public byte[] title = new byte[128];
    public byte priority;
    public ushort npcHandle;
    public SHINE_XY_TYPE npcPosition = new();
    public ushort limitRange;
    public byte menunum;
    public SERVERMENU[] menu = [];

    public void Read(BinaryReader reader)
    {
        title = reader.ReadBytes(128);
        priority = reader.ReadByte();
        npcHandle = reader.ReadUInt16();
        npcPosition.Read(reader);
        limitRange = reader.ReadUInt16();
        menunum = reader.ReadByte();
        menu = new SERVERMENU[menunum];
        for (int i = 0; i < menunum; i++)
        {
            menu[i] = new SERVERMENU();
            menu[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(title, 0, 128);
        writer.Write(priority);
        writer.Write(npcHandle);
        npcPosition.Write(writer);
        writer.Write(limitRange);
        writer.Write(menunum);
        for (int i = 0; i < menu.Length; i++)
            menu[i].Write(writer);
    }
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_MENU_SHOPOPEN_CMD : IFiestaPacketBody
{
    public ushort itemnum;
    public ushort npc;
    // PROTO_NC_MENU_SHOPOPEN_CMD::MENUITEM[0] itemlist at offset 4 (unsupported type)

    public void Read(BinaryReader reader)
    {
        itemnum = reader.ReadUInt16();
        npc = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemnum);
        writer.Write(npc);
    }
}

/// <summary>
/// Department: Menu (0x0F) | Opcode: 5 | Full: 0x3C05
/// sizeof = 24
/// </summary>
[FiestaOpcode(ProtocolCommand.Menu, 5)]
public class PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD : IFiestaPacketBody
{
    // PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU hp at offset 0 (unsupported type)
    // PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU sp at offset 12 (unsupported type)

    public void Read(BinaryReader reader)
    {
        reader.ReadBytes(12); // skip PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU hp
        reader.ReadBytes(12); // skip PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU sp
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(new byte[12]); // skip PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU hp
        writer.Write(new byte[12]); // skip PROTO_NC_MENU_SHOPOPENSOULSTONE_CMD::SOULSTONEMENU sp
    }
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_MENU_SHOPOPENTABLE_CMD : IFiestaPacketBody
{
    public ushort itemnum;
    public ushort npc;
    // PROTO_NC_MENU_SHOPOPENTABLE_CMD::MENUITEM[0] itemlist at offset 4 (unsupported type)

    public void Read(BinaryReader reader)
    {
        itemnum = reader.ReadUInt16();
        npc = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(itemnum);
        writer.Write(npc);
    }
}

