// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Pet (0x35) | Opcode: 6 | Full: 0x3506
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 6)]
public class PROTO_NC_PET_ASK_NEW_NAME_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nPetHandle;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nPetHandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nPetHandle);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 5 | Full: 0x3505
/// sizeof = 7
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 5)]
public class PROTO_NC_PET_ASK_NEW_NAME_REQ : IFiestaPacketBody
{
    public ushort nPetHandle;
    public uint nPetID;
    public byte nFirstSummon;

    public void Read(BinaryReader reader)
    {
        nPetHandle = reader.ReadUInt16();
        nPetID = reader.ReadUInt32();
        nFirstSummon = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPetHandle);
        writer.Write(nPetID);
        writer.Write(nFirstSummon);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 14 | Full: 0x350E
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 14)]
public class PROTO_NC_PET_CREATE_DB_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nMasterHandle;
    public uint nPetRegNum;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 13 | Full: 0x350D
/// sizeof = 24
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 13)]
public class PROTO_NC_PET_CREATE_DB_REQ : IFiestaPacketBody
{
    public ushort nMasterHandle;
    public uint nMasterRegNo;
    public Name4 sPetName = new();
    public byte nPetMind;
    public byte nPetStress;

    public void Read(BinaryReader reader)
    {
        nMasterHandle = reader.ReadUInt16();
        nMasterRegNo = reader.ReadUInt32();
        sPetName.Read(reader);
        nPetMind = reader.ReadByte();
        nPetStress = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMasterHandle);
        writer.Write(nMasterRegNo);
        sPetName.Write(writer);
        writer.Write(nPetMind);
        writer.Write(nPetStress);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 18 | Full: 0x3512
/// sizeof = 23
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 18)]
public class PROTO_NC_PET_LINK_RESUMMON_CMD : IFiestaPacketBody
{
    public uint nCharNo;
    public byte bDoResummon;
    public ulong xResummonCode;
    public ushort nSummonSlot;
    public uint nId;
    public uint nRegNum;

    public void Read(BinaryReader reader)
    {
        nCharNo = reader.ReadUInt32();
        bDoResummon = reader.ReadByte();
        xResummonCode = reader.ReadUInt64();
        nSummonSlot = reader.ReadUInt16();
        nId = reader.ReadUInt32();
        nRegNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nCharNo);
        writer.Write(bDoResummon);
        writer.Write(xResummonCode);
        writer.Write(nSummonSlot);
        writer.Write(nId);
        writer.Write(nRegNum);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 12 | Full: 0x350C
/// sizeof = 26
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 12)]
public class PROTO_NC_PET_LOAD_INFO_DB_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nMasterHandle;
    public uint nPetRegNum;
    public Name4 sPetName = new();
    public byte nPetMind;
    public byte nPetStress;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
        sPetName.Read(reader);
        nPetMind = reader.ReadByte();
        nPetStress = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
        sPetName.Write(writer);
        writer.Write(nPetMind);
        writer.Write(nPetStress);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 11 | Full: 0x350B
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 11)]
public class PROTO_NC_PET_LOAD_INFO_DB_REQ : IFiestaPacketBody
{
    public ushort nMasterHandle;
    public uint nPetRegNum;

    public void Read(BinaryReader reader)
    {
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 8 | Full: 0x3508
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 8)]
public class PROTO_NC_PET_SET_NAME_ACK : IFiestaPacketBody
{
    public ushort nError;
    public uint nPetID;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nPetID = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nPetID);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 10 | Full: 0x350A
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 10)]
public class PROTO_NC_PET_SET_NAME_CANCEL_ACK : IFiestaPacketBody
{
    public ushort nError;
    public uint nPetID;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nPetID = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nPetID);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 9 | Full: 0x3509
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 9)]
public class PROTO_NC_PET_SET_NAME_CANCEL_REQ : IFiestaPacketBody
{
    public ushort nPetHandle;

    public void Read(BinaryReader reader)
    {
        nPetHandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPetHandle);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 19 | Full: 0x3513
/// sizeof = 18
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 19)]
public class PROTO_NC_PET_SET_NAME_CMD : IFiestaPacketBody
{
    public ushort nPetHandle;
    public Name4 sPetName = new();

    public void Read(BinaryReader reader)
    {
        nPetHandle = reader.ReadUInt16();
        sPetName.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPetHandle);
        sPetName.Write(writer);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 4 | Full: 0x3504
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 4)]
public class PROTO_NC_PET_SET_NAME_DB_ACK : IFiestaPacketBody
{
    public ushort nError;
    public ushort nMasterHandle;
    public uint nPetRegNum;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 3 | Full: 0x3503
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 3)]
public class PROTO_NC_PET_SET_NAME_DB_REQ : IFiestaPacketBody
{
    public ushort nMasterHandle;
    public uint nPetRegNum;
    public Name4 sPetName = new();

    public void Read(BinaryReader reader)
    {
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
        sPetName.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
        sPetName.Write(writer);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 7 | Full: 0x3507
/// sizeof = 18
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 7)]
public class PROTO_NC_PET_SET_NAME_REQ : IFiestaPacketBody
{
    public ushort nPetHandle;
    public Name4 sPetName = new();

    public void Read(BinaryReader reader)
    {
        nPetHandle = reader.ReadUInt16();
        sPetName.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nPetHandle);
        sPetName.Write(writer);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 1 | Full: 0x3501
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 1)]
public class PROTO_NC_PET_SET_TENDENCY_DB_REQ : IFiestaPacketBody
{
    public ushort nMasterHandle;
    public uint nPetRegNum;
    public byte nPetMind;
    public byte nPetStress;

    public void Read(BinaryReader reader)
    {
        nMasterHandle = reader.ReadUInt16();
        nPetRegNum = reader.ReadUInt32();
        nPetMind = reader.ReadByte();
        nPetStress = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMasterHandle);
        writer.Write(nPetRegNum);
        writer.Write(nPetMind);
        writer.Write(nPetStress);
    }
}

/// <summary>
/// Department: Pet (0x35) | Opcode: 17 | Full: 0x3511
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Pet, 17)]
public class PROTO_NC_PET_USE_ITEM_FAIL_ACK : IFiestaPacketBody
{
    public ushort nError;

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
    }
}

