// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Prison (0x1F) | Opcode: 2 | Full: 0x7C02
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 2)]
public class PROTO_NC_PRISON_ADD_GM_ACK : IFiestaPacketBody
{
    public Name5 sImprison = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        sImprison.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        sImprison.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 1 | Full: 0x7C01
/// sizeof = 102
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 1)]
public class PROTO_NC_PRISON_ADD_GM_REQ : IFiestaPacketBody
{
    public Name5 sImprison = new();
    public ushort nMinute;
    public sbyte[] sReason = new sbyte[16];
    public sbyte[] sRemark = new sbyte[64];

    public void Read(BinaryReader reader)
    {
        sImprison.Read(reader);
        nMinute = reader.ReadUInt16();
        for (int i = 0; i < 16; i++)
            sReason[i] = reader.ReadSByte();
        for (int i = 0; i < 64; i++)
            sRemark[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        sImprison.Write(writer);
        writer.Write(nMinute);
        for (int i = 0; i < 16; i++)
            writer.Write(sReason[i]);
        for (int i = 0; i < 64; i++)
            writer.Write(sRemark[i]);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 10 | Full: 0x7C0A
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 10)]
public class PROTO_NC_PRISON_ALTER_GM_ACK : IFiestaPacketBody
{
    public Name5 sImprison = new();
    public ushort err;

    public void Read(BinaryReader reader)
    {
        sImprison.Read(reader);
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        sImprison.Write(writer);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 9 | Full: 0x7C09
/// sizeof = 102
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 9)]
public class PROTO_NC_PRISON_ALTER_GM_REQ : IFiestaPacketBody
{
    public Name5 sImprison = new();
    public ushort nMin;
    public sbyte[] sReason = new sbyte[16];
    public sbyte[] sRemark = new sbyte[64];

    public void Read(BinaryReader reader)
    {
        sImprison.Read(reader);
        nMin = reader.ReadUInt16();
        for (int i = 0; i < 16; i++)
            sReason[i] = reader.ReadSByte();
        for (int i = 0; i < 64; i++)
            sRemark[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        sImprison.Write(writer);
        writer.Write(nMin);
        for (int i = 0; i < 16; i++)
            writer.Write(sReason[i]);
        for (int i = 0; i < 64; i++)
            writer.Write(sRemark[i]);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 5 | Full: 0x7C05
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 5)]
public class PROTO_NC_PRISON_END_ACK : IFiestaPacketBody
{
    public ushort err;
    public uint nPrisonSecond;

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        nPrisonSecond = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        writer.Write(nPrisonSecond);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 4 | Full: 0x7C04
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 4)]
public class PROTO_NC_PRISON_END_REQ : IFiestaPacketBody
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 7 | Full: 0x7C07
/// sizeof = 84
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 7)]
public class PROTO_NC_PRISON_GET_ACK : IFiestaPacketBody
{
    public ushort err;
    public ushort nMinute;
    public sbyte[] sReason = new sbyte[16];
    public sbyte[] sRemark = new sbyte[64];

    public void Read(BinaryReader reader)
    {
        err = reader.ReadUInt16();
        nMinute = reader.ReadUInt16();
        for (int i = 0; i < 16; i++)
            sReason[i] = reader.ReadSByte();
        for (int i = 0; i < 64; i++)
            sRemark[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(err);
        writer.Write(nMinute);
        for (int i = 0; i < 16; i++)
            writer.Write(sReason[i]);
        for (int i = 0; i < 64; i++)
            writer.Write(sRemark[i]);
    }
}

/// <summary>
/// Department: Prison (0x1F) | Opcode: 3 | Full: 0x7C03
/// sizeof = 82
/// </summary>
[FiestaOpcode(ProtocolCommand.Prison, 3)]
public class PROTO_NC_PRISON_OK_CMD : IFiestaPacketBody
{
    public ushort nMinute;
    public sbyte[] sReason = new sbyte[16];
    public sbyte[] sRemark = new sbyte[64];

    public void Read(BinaryReader reader)
    {
        nMinute = reader.ReadUInt16();
        for (int i = 0; i < 16; i++)
            sReason[i] = reader.ReadSByte();
        for (int i = 0; i < 64; i++)
            sRemark[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMinute);
        for (int i = 0; i < 16; i++)
            writer.Write(sReason[i]);
        for (int i = 0; i < 64; i++)
            writer.Write(sRemark[i]);
    }
}

