// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 14</summary>
public class PROTO_NC_PROMOTION_DB_REWARD_ACK
{
    public uint nUserNo;
    public byte nWorldNo;
    public uint nCharNo;
    public byte nClass;
    public byte nLevel;
    public ushort DBError;
    public byte nNumOfItems;
    // PROTO_NC_PROMOTION_DB_REWARD_ACK::<unnamed-type-RewardList>[0] RewardList at offset 14 (unsupported type)

    public void Read(BinaryReader reader)
    {
        nUserNo = reader.ReadUInt32();
        nWorldNo = reader.ReadByte();
        nCharNo = reader.ReadUInt32();
        nClass = reader.ReadByte();
        nLevel = reader.ReadByte();
        DBError = reader.ReadUInt16();
        nNumOfItems = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nUserNo);
        writer.Write(nWorldNo);
        writer.Write(nCharNo);
        writer.Write(nClass);
        writer.Write(nLevel);
        writer.Write(DBError);
        writer.Write(nNumOfItems);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_PROMOTION_REWARD_ITEM_CMD
{
    public byte nNumOfItems;
    // PROTO_NC_PROMOTION_REWARD_ITEM_CMD::<unnamed-type-RewardList>[0] RewardList at offset 1 (unsupported type)

    public void Read(BinaryReader reader)
    {
        nNumOfItems = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nNumOfItems);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

