// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 34</summary>
public class PROTO_NC_SCENARIO_ANIMATE_CMD
{
    public ushort handle;
    public Name8 anicode = new();

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        anicode.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        anicode.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_SCENARIO_AREAENTRY_ACK
{
    public Name8 areaindex = new();

    public void Read(BinaryReader reader)
    {
        areaindex.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        areaindex.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_SCENARIO_AREAENTRY_REQ
{
    public Name8 areaindex = new();

    public void Read(BinaryReader reader)
    {
        areaindex.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        areaindex.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_SCENARIO_AREALEAVE_ACK
{
    public Name8 areaindex = new();

    public void Read(BinaryReader reader)
    {
        areaindex.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        areaindex.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_SCENARIO_AREALEAVE_REQ
{
    public Name8 areaindex = new();

    public void Read(BinaryReader reader)
    {
        areaindex.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        areaindex.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SCENARIO_BRIEFEFFECT_CMD
{
    public byte effectcode;

    public void Read(BinaryReader reader)
    {
        effectcode = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(effectcode);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 15</summary>
public class PROTO_NC_SCENARIO_CAMERA_MOVE_CMD
{
    public byte MoveType;
    public SHINE_XY_TYPE ViewCoord = new();
    public ushort AngleXZ;
    public ushort AngleY;
    public ushort Dist;

    public void Read(BinaryReader reader)
    {
        MoveType = reader.ReadByte();
        ViewCoord.Read(reader);
        AngleXZ = reader.ReadUInt16();
        AngleY = reader.ReadUInt16();
        Dist = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(MoveType);
        ViewCoord.Write(writer);
        writer.Write(AngleXZ);
        writer.Write(AngleY);
        writer.Write(Dist);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_CHATWIN_CMD
{
    public ushort mob;
    public byte len;
    public byte[] content = [];

    public void Read(BinaryReader reader)
    {
        mob = reader.ReadUInt16();
        len = reader.ReadByte();
        content = reader.ReadBytes(len);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mob);
        writer.Write(len);
        writer.Write(content);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SCENARIO_DEL_DIRECTIONAL_ARROW_CMD
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_SCENARIO_DIALOG_CMD
{
    public sbyte[] sFacecutIndex = new sbyte[33];
    public byte nLen;
    public byte[] sContents = [];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 33; i++)
            sFacecutIndex[i] = reader.ReadSByte();
        nLen = reader.ReadByte();
        sContents = reader.ReadBytes(nLen);
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 33; i++)
            writer.Write(sFacecutIndex[i]);
        writer.Write(nLen);
        writer.Write(sContents);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_SCENARIO_DIRECTIONAL_ARROW_CMD
{
    public SHINE_XY_TYPE DirectionalPos = new();

    public void Read(BinaryReader reader)
    {
        DirectionalPos.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        DirectionalPos.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_DOORSTATE_CMD
{
    public ushort door;
    public byte doorstate;

    public void Read(BinaryReader reader)
    {
        door = reader.ReadUInt16();
        doorstate = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(door);
        writer.Write(doorstate);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_EFFECT_TIMER_CMD
{
    public byte nTimerFunction;
    public ushort nSecond;

    public void Read(BinaryReader reader)
    {
        nTimerFunction = reader.ReadByte();
        nSecond = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nTimerFunction);
        writer.Write(nSecond);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_FOG_CMD
{
    public byte fog;
    public ushort depth;

    public void Read(BinaryReader reader)
    {
        fog = reader.ReadByte();
        depth = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(fog);
        writer.Write(depth);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SCENARIO_HIDE_OTHER_PLAYER_CMD
{
    public byte bIsHide;

    public void Read(BinaryReader reader)
    {
        bIsHide = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(bIsHide);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_LIGHT_CMD
{
    public byte red;
    public byte green;
    public byte blue;

    public void Read(BinaryReader reader)
    {
        red = reader.ReadByte();
        green = reader.ReadByte();
        blue = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(red);
        writer.Write(green);
        writer.Write(blue);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 37</summary>
public class PROTO_NC_SCENARIO_MAP_OBJECT_CONTROL_CMD
{
    public sbyte[] sObjectIndex = new sbyte[32];
    public byte IsEnableObject;
    // MAP_OBJECT_CONTROL_TYPE eControlType at offset 33 (unsupported type)

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 32; i++)
            sObjectIndex[i] = reader.ReadSByte();
        IsEnableObject = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 32; i++)
            writer.Write(sObjectIndex[i]);
        writer.Write(IsEnableObject);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_SCENARIO_MAPMARK_CMD
{
    public ushort nNum;
    // PROTO_NC_SCENARIO_MAPMARK_CMD::IconInfo[0] IconList at offset 2 (unsupported type)

    public void Read(BinaryReader reader)
    {
        nNum = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nNum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 17</summary>
public class PROTO_NC_SCENARIO_MESSAGE_CMD
{
    public sbyte[] DialogIndex = new sbyte[17];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 17; i++)
            DialogIndex[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 17; i++)
            writer.Write(DialogIndex[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_SCENARIO_MESSAGENOTICE_CMD
{
    public uint message;

    public void Read(BinaryReader reader)
    {
        message = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(message);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 35</summary>
public class PROTO_NC_SCENARIO_NPCCHAT_CMD
{
    public sbyte[] DialogIndex = new sbyte[33];
    public ushort NPCHandle;

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 33; i++)
            DialogIndex[i] = reader.ReadSByte();
        NPCHandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 33; i++)
            writer.Write(DialogIndex[i]);
        writer.Write(NPCHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SCENARIO_OBJTYPECHANGE_CMD
{
    public ushort handle;
    public byte type;

    public void Read(BinaryReader reader)
    {
        handle = reader.ReadUInt16();
        type = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(handle);
        writer.Write(type);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1000</summary>
public class PROTO_NC_SCENARIO_RANKING_LIST_CMD
{
    public SCENARIO_RANKING_INFO[] PreviousRanking = new SCENARIO_RANKING_INFO[20];
    public SCENARIO_RANKING_INFO[] CurrentRanking = new SCENARIO_RANKING_INFO[20];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 20; i++)
        {
            PreviousRanking[i] = new SCENARIO_RANKING_INFO();
            PreviousRanking[i].Read(reader);
        }
        for (int i = 0; i < 20; i++)
        {
            CurrentRanking[i] = new SCENARIO_RANKING_INFO();
            CurrentRanking[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 20; i++)
            PreviousRanking[i].Write(writer);
        for (int i = 0; i < 20; i++)
            CurrentRanking[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 37</summary>
public class PROTO_NC_SCENARIO_SCRIPTMESSAGE_CMD
{
    public sbyte[] DialogIndex = new sbyte[32];
    public byte[] nlen = new byte[5];
    public byte[] sContent = [];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 32; i++)
            DialogIndex[i] = reader.ReadSByte();
        nlen = reader.ReadBytes(5);
        // TODO: sContent is variable-length but count field not detected
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 32; i++)
            writer.Write(DialogIndex[i]);
        writer.Write(nlen, 0, 5);
        writer.Write(sContent);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SCENARIO_SYSTEM_MESSAGE_CMD
{
    public byte nLen;
    public byte[] sMessage = [];

    public void Read(BinaryReader reader)
    {
        nLen = reader.ReadByte();
        sMessage = reader.ReadBytes(nLen);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nLen);
        writer.Write(sMessage);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_SCENARIO_TIMER_CMD
{
    public ushort nSecond;

    public void Read(BinaryReader reader)
    {
        nSecond = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nSecond);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_SCENARIO_TIMER_END_CMD
{
    public uint nDeleteSec;

    public void Read(BinaryReader reader)
    {
        nDeleteSec = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nDeleteSec);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SCENARIO_TIMER_START_CMD
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 13</summary>
public class PROTO_NC_SCENARIO_TOPVIEW_CMD
{
    public byte nMoveType;
    public SHINE_XY_TYPE CenterPos = new();
    public ushort nDistance;
    public ushort nAngle;

    public void Read(BinaryReader reader)
    {
        nMoveType = reader.ReadByte();
        CenterPos.Read(reader);
        nDistance = reader.ReadUInt16();
        nAngle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nMoveType);
        CenterPos.Write(writer);
        writer.Write(nDistance);
        writer.Write(nAngle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

