// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 6</summary>
public class PROTO_NC_SKILL_COOLTIME_CMD
{
    public ushort skill;
    public uint sec;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        sec = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(sec);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_SKILL_EMPOW_RESET_DB_REQ
{
    public ushort zonehandle;
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SKILL_EMPOW_RESET_SUC_ACK
{
    public byte totalempow;

    public void Read(BinaryReader reader)
    {
        totalempow = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(totalempow);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_SKILL_EMPOWALLOC_ACK
{
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 13</summary>
public class PROTO_NC_SKILL_EMPOWALLOC_DB_ACK
{
    public ushort zonehandle;
    public uint chrregnum;
    public ushort lockindex;
    public ushort skill;
    public ushort err;
    public byte bUseItem;

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        lockindex = reader.ReadUInt16();
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
        bUseItem = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
        writer.Write(lockindex);
        writer.Write(skill);
        writer.Write(err);
        writer.Write(bUseItem);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 40</summary>
public class PROTO_NC_SKILL_EMPOWALLOC_DB_REQ
{
    public ushort zonehandle;
    public uint chrregnum;
    public ushort lockindex;
    public ushort skill;
    public byte bUseItem;
    public PROTO_NC_SKILL_EMPOWALLOC_REQ empower = new();
    public PROTO_ITEMDELETEREQUEST redistitem = new();

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        lockindex = reader.ReadUInt16();
        skill = reader.ReadUInt16();
        bUseItem = reader.ReadByte();
        empower.Read(reader);
        redistitem.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
        writer.Write(lockindex);
        writer.Write(skill);
        writer.Write(bUseItem);
        empower.Write(writer);
        redistitem.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_SKILL_EMPOWALLOC_REQ
{
    public ushort skill;
    public SKILL_EMPOWER plus = new();
    public SKILL_EMPOWER minus = new();

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        plus.Read(reader);
        minus.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        plus.Write(writer);
        minus.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_SKILL_EMPOWPOINT_CMD
{
    public byte restempow;

    public void Read(BinaryReader reader)
    {
        restempow = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(restempow);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_SKILL_ERASE_ACK
{
    public NETPACKETZONEHEADER header = new();
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(skill);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_SKILL_ERASE_REQ
{
    public NETPACKETZONEHEADER header = new();
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(skill);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 21</summary>
public class PROTO_NC_SKILL_JUMP_CMD
{
    public ushort nObject;
    public SHINE_XY_TYPE From = new();
    public SHINE_XY_TYPE To = new();
    public byte nDirect;
    public ushort SkillID;

    public void Read(BinaryReader reader)
    {
        nObject = reader.ReadUInt16();
        From.Read(reader);
        To.Read(reader);
        nDirect = reader.ReadByte();
        SkillID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nObject);
        From.Write(writer);
        To.Write(writer);
        writer.Write(nDirect);
        writer.Write(SkillID);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_SKILL_PASSIVESKILL_LEARN_CMD
{
    public ushort wmshandle;
    public uint chrregnum;
    public ushort passiveskillid;

    public void Read(BinaryReader reader)
    {
        wmshandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        passiveskillid = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wmshandle);
        writer.Write(chrregnum);
        writer.Write(passiveskillid);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_SKILL_PRODUCTFIELD_ACK
{
    public ushort mainskill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        mainskill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mainskill);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_SKILL_PRODUCTFIELD_REQ
{
    public ushort mainskill;

    public void Read(BinaryReader reader)
    {
        mainskill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mainskill);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_SKILL_REVIVE_CMD
{
    public uint hp;
    public uint sp;
    public uint lp;

    public void Read(BinaryReader reader)
    {
        hp = reader.ReadUInt32();
        sp = reader.ReadUInt32();
        lp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hp);
        writer.Write(sp);
        writer.Write(lp);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_SKILL_SKILLEXP_CLIENT_CMD
{
    public ushort skill;
    public uint mastery;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        mastery = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(mastery);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_SKILL_SKILLTEACH_REQ
{
    public uint chrregnum;
    public ushort skillid;
    public byte ispassive;
    public ushort removeid;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        skillid = reader.ReadUInt16();
        ispassive = reader.ReadByte();
        removeid = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(skillid);
        writer.Write(ispassive);
        writer.Write(removeid);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SKILL_SKILLTEACHSUC_ACK
{
    public ushort skillid;
    public byte ispassive;

    public void Read(BinaryReader reader)
    {
        skillid = reader.ReadUInt16();
        ispassive = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skillid);
        writer.Write(ispassive);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 14</summary>
public class PROTO_NC_SKILL_SOMEONEREVIVE_CMD
{
    public ushort reviver;
    public uint hp;
    public uint sp;
    public uint lp;

    public void Read(BinaryReader reader)
    {
        reviver = reader.ReadUInt16();
        hp = reader.ReadUInt32();
        sp = reader.ReadUInt32();
        lp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(reviver);
        writer.Write(hp);
        writer.Write(sp);
        writer.Write(lp);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_SKILL_UNLEARN_ACK
{
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(err);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_SKILL_UNLEARN_REQ
{
    public byte slot;
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        slot = reader.ReadByte();
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slot);
        writer.Write(skill);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 20</summary>
public class PROTO_NC_SKILL_WARP_CMD
{
    public ushort @object;
    public SHINE_XY_TYPE from = new();
    public SHINE_XY_TYPE to = new();
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        @object = reader.ReadUInt16();
        from.Read(reader);
        to.Read(reader);
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(@object);
        from.Write(writer);
        to.Write(writer);
        writer.Write(skill);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

