// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Skill (0x12) | Opcode: 33 | Full: 0x4821
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 33)]
public class PROTO_NC_SKILL_COOLTIME_CMD : IFiestaPacketBody
{
    public ushort skill;
    public uint sec;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        sec = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(sec);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 11 | Full: 0x480B
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 11)]
public class PROTO_NC_SKILL_EMPOW_RESET_DB_REQ : IFiestaPacketBody
{
    public ushort zonehandle;
    public uint chrregnum;

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 15 | Full: 0x480F
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 15)]
public class PROTO_NC_SKILL_EMPOW_RESET_SUC_ACK : IFiestaPacketBody
{
    public byte totalempow;

    public void Read(BinaryReader reader)
    {
        totalempow = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(totalempow);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 20 | Full: 0x4814
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 20)]
public class PROTO_NC_SKILL_EMPOWALLOC_ACK : IFiestaPacketBody
{
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 19 | Full: 0x4813
/// sizeof = 13
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 19)]
public class PROTO_NC_SKILL_EMPOWALLOC_DB_ACK : IFiestaPacketBody
{
    public ushort zonehandle;
    public uint chrregnum;
    public ushort lockindex;
    public ushort skill;
    public ushort err;
    public byte bUseItem;

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        lockindex = reader.ReadUInt16();
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
        bUseItem = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
        writer.Write(lockindex);
        writer.Write(skill);
        writer.Write(err);
        writer.Write(bUseItem);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 18 | Full: 0x4812
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 18)]
public class PROTO_NC_SKILL_EMPOWALLOC_DB_REQ : IFiestaPacketBody
{
    public ushort zonehandle;
    public uint chrregnum;
    public ushort lockindex;
    public ushort skill;
    public byte bUseItem;
    public PROTO_NC_SKILL_EMPOWALLOC_REQ empower = new();
    public PROTO_ITEMDELETEREQUEST redistitem = new();

    public void Read(BinaryReader reader)
    {
        zonehandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        lockindex = reader.ReadUInt16();
        skill = reader.ReadUInt16();
        bUseItem = reader.ReadByte();
        empower.Read(reader);
        redistitem.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(zonehandle);
        writer.Write(chrregnum);
        writer.Write(lockindex);
        writer.Write(skill);
        writer.Write(bUseItem);
        empower.Write(writer);
        redistitem.Write(writer);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 17 | Full: 0x4811
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 17)]
public class PROTO_NC_SKILL_EMPOWALLOC_REQ : IFiestaPacketBody
{
    public ushort skill;
    public SKILL_EMPOWER plus = new();
    public SKILL_EMPOWER minus = new();

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        plus.Read(reader);
        minus.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        plus.Write(writer);
        minus.Write(writer);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 16 | Full: 0x4810
/// sizeof = 1
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 16)]
public class PROTO_NC_SKILL_EMPOWPOINT_CMD : IFiestaPacketBody
{
    public byte restempow;

    public void Read(BinaryReader reader)
    {
        restempow = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(restempow);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 38 | Full: 0x4826
/// sizeof = 10
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 38)]
public class PROTO_NC_SKILL_ERASE_ACK : IFiestaPacketBody
{
    public NETPACKETZONEHEADER header = new();
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(skill);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 37 | Full: 0x4825
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 37)]
public class PROTO_NC_SKILL_ERASE_REQ : IFiestaPacketBody
{
    public NETPACKETZONEHEADER header = new();
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        header.Read(reader);
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        header.Write(writer);
        writer.Write(skill);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 45 | Full: 0x482D
/// sizeof = 21
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 45)]
public class PROTO_NC_SKILL_JUMP_CMD : IFiestaPacketBody
{
    public ushort nObject;
    public SHINE_XY_TYPE From = new();
    public SHINE_XY_TYPE To = new();
    public byte nDirect;
    public ushort SkillID;

    public void Read(BinaryReader reader)
    {
        nObject = reader.ReadUInt16();
        From.Read(reader);
        To.Read(reader);
        nDirect = reader.ReadByte();
        SkillID = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nObject);
        From.Write(writer);
        To.Write(writer);
        writer.Write(nDirect);
        writer.Write(SkillID);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 32 | Full: 0x4820
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 32)]
public class PROTO_NC_SKILL_PASSIVESKILL_LEARN_CMD : IFiestaPacketBody
{
    public ushort wmshandle;
    public uint chrregnum;
    public ushort passiveskillid;

    public void Read(BinaryReader reader)
    {
        wmshandle = reader.ReadUInt16();
        chrregnum = reader.ReadUInt32();
        passiveskillid = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(wmshandle);
        writer.Write(chrregnum);
        writer.Write(passiveskillid);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 35 | Full: 0x4823
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 35)]
public class PROTO_NC_SKILL_PRODUCTFIELD_ACK : IFiestaPacketBody
{
    public ushort mainskill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        mainskill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mainskill);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 34 | Full: 0x4822
/// sizeof = 2
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 34)]
public class PROTO_NC_SKILL_PRODUCTFIELD_REQ : IFiestaPacketBody
{
    public ushort mainskill;

    public void Read(BinaryReader reader)
    {
        mainskill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(mainskill);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 30 | Full: 0x481E
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 30)]
public class PROTO_NC_SKILL_REVIVE_CMD : IFiestaPacketBody
{
    public uint hp;
    public uint sp;
    public uint lp;

    public void Read(BinaryReader reader)
    {
        hp = reader.ReadUInt32();
        sp = reader.ReadUInt32();
        lp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hp);
        writer.Write(sp);
        writer.Write(lp);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 29 | Full: 0x481D
/// sizeof = 6
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 29)]
public class PROTO_NC_SKILL_SKILLEXP_CLIENT_CMD : IFiestaPacketBody
{
    public ushort skill;
    public uint mastery;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        mastery = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(mastery);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 1 | Full: 0x4801
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 1)]
public class PROTO_NC_SKILL_SKILLTEACH_REQ : IFiestaPacketBody
{
    public uint chrregnum;
    public ushort skillid;
    public byte ispassive;
    public ushort removeid;

    public void Read(BinaryReader reader)
    {
        chrregnum = reader.ReadUInt32();
        skillid = reader.ReadUInt16();
        ispassive = reader.ReadByte();
        removeid = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(chrregnum);
        writer.Write(skillid);
        writer.Write(ispassive);
        writer.Write(removeid);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 2 | Full: 0x4802
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 2)]
public class PROTO_NC_SKILL_SKILLTEACHSUC_ACK : IFiestaPacketBody
{
    public ushort skillid;
    public byte ispassive;

    public void Read(BinaryReader reader)
    {
        skillid = reader.ReadUInt16();
        ispassive = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skillid);
        writer.Write(ispassive);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 31 | Full: 0x481F
/// sizeof = 14
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 31)]
public class PROTO_NC_SKILL_SOMEONEREVIVE_CMD : IFiestaPacketBody
{
    public ushort reviver;
    public uint hp;
    public uint sp;
    public uint lp;

    public void Read(BinaryReader reader)
    {
        reviver = reader.ReadUInt16();
        hp = reader.ReadUInt32();
        sp = reader.ReadUInt32();
        lp = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(reviver);
        writer.Write(hp);
        writer.Write(sp);
        writer.Write(lp);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 39 | Full: 0x4827
/// sizeof = 4
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 39)]
public class PROTO_NC_SKILL_UNLEARN_ACK : IFiestaPacketBody
{
    public ushort skill;
    public ushort err;

    public void Read(BinaryReader reader)
    {
        skill = reader.ReadUInt16();
        err = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(skill);
        writer.Write(err);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 36 | Full: 0x4824
/// sizeof = 3
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 36)]
public class PROTO_NC_SKILL_UNLEARN_REQ : IFiestaPacketBody
{
    public byte slot;
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        slot = reader.ReadByte();
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slot);
        writer.Write(skill);
    }
}

/// <summary>
/// Department: Skill (0x12) | Opcode: 40 | Full: 0x4828
/// sizeof = 20
/// </summary>
[FiestaOpcode(ProtocolCommand.Skill, 40)]
public class PROTO_NC_SKILL_WARP_CMD : IFiestaPacketBody
{
    public ushort @object;
    public SHINE_XY_TYPE from = new();
    public SHINE_XY_TYPE to = new();
    public ushort skill;

    public void Read(BinaryReader reader)
    {
        @object = reader.ReadUInt16();
        from.Read(reader);
        to.Read(reader);
        skill = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(@object);
        from.Write(writer);
        to.Write(writer);
        writer.Write(skill);
    }
}

