// <auto-generated />
using FiestaLibReloaded.Networking;
using FiestaLibReloaded.Networking.Enums;

namespace FiestaLibReloaded.Networking.Structs;

/// <summary>
/// Department: Syslog (0x32) | Opcode: 2 | Full: 0x3202
/// sizeof = 296
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 2)]
public class PROTO_NC_SYSLOG_ACCOUNT_LOGIN_FAILURE : IFiestaPacketBody
{
    public sbyte[] UserName = new sbyte[260];
    public Name4 UserIP = new();
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 260; i++)
            UserName[i] = reader.ReadSByte();
        UserIP.Read(reader);
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 260; i++)
            writer.Write(UserName[i]);
        UserIP.Write(writer);
        spawnapps.Write(writer);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 1 | Full: 0x3201
/// sizeof = 40
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 1)]
public class PROTO_NC_SYSLOG_ACCOUNT_LOGIN_SUCCESS : IFiestaPacketBody
{
    public uint UserNo;
    public Name4 UserIP = new();
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        UserIP.Read(reader);
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        UserIP.Write(writer);
        spawnapps.Write(writer);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 3 | Full: 0x3203
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 3)]
public class PROTO_NC_SYSLOG_ACCOUNT_LOGOUT : IFiestaPacketBody
{
    public uint UserNo;
    public uint LoginKeepTime;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        LoginKeepTime = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(LoginKeepTime);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 4 | Full: 0x3204
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 4)]
public class PROTO_NC_SYSLOG_CHAR_CREATED : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte CharClass;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        CharClass = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(CharClass);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 10 | Full: 0x320A
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 10)]
public class PROTO_NC_SYSLOG_CHAR_DEATH : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte ZoneNo;
    public byte AttackerType;
    public uint AttackerID;
    public SHINE_XY_TYPE DeathCoord = new();

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        ZoneNo = reader.ReadByte();
        AttackerType = reader.ReadByte();
        AttackerID = reader.ReadUInt32();
        DeathCoord.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(ZoneNo);
        writer.Write(AttackerType);
        writer.Write(AttackerID);
        DeathCoord.Write(writer);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 5 | Full: 0x3205
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 5)]
public class PROTO_NC_SYSLOG_CHAR_DELETED : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte CharClass;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        CharClass = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(CharClass);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 6 | Full: 0x3206
/// sizeof = 8
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 6)]
public class PROTO_NC_SYSLOG_CHAR_ENTER_GAME : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 7 | Full: 0x3207
/// sizeof = 12
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 7)]
public class PROTO_NC_SYSLOG_CHAR_LEAVE_GAME : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public uint PlayTime;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        PlayTime = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(PlayTime);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 8 | Full: 0x3208
/// sizeof = 9
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 8)]
public class PROTO_NC_SYSLOG_CHAR_LEVEL_UP : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte CharLev;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        CharLev = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(CharLev);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 15 | Full: 0x320F
/// sizeof = 13
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 15)]
public class PROTO_NC_SYSLOG_CHAR_QUEST_STARTED : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public ushort QuestID;
    public byte ZoneNo;
    public ushort QuestStartNPC;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        QuestID = reader.ReadUInt16();
        ZoneNo = reader.ReadByte();
        QuestStartNPC = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(QuestID);
        writer.Write(ZoneNo);
        writer.Write(QuestStartNPC);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 11 | Full: 0x320B
/// sizeof = 22
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 11)]
public class PROTO_NC_SYSLOG_CHAR_VICTORY : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte ZoneNo;
    public byte TargetType;
    public uint TargetID;
    public SHINE_XY_TYPE KillCoord = new();

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        ZoneNo = reader.ReadByte();
        TargetType = reader.ReadByte();
        TargetID = reader.ReadUInt32();
        KillCoord.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(ZoneNo);
        writer.Write(TargetType);
        writer.Write(TargetID);
        KillCoord.Write(writer);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 9 | Full: 0x3209
/// sizeof = 11
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 9)]
public class PROTO_NC_SYSLOG_CHAR_ZONE_TRANSITION : IFiestaPacketBody
{
    public uint UserNo;
    public uint CharNo;
    public byte DestZoneNo;
    public byte SrcZoneNo;
    public byte CharLev;

    public void Read(BinaryReader reader)
    {
        UserNo = reader.ReadUInt32();
        CharNo = reader.ReadUInt32();
        DestZoneNo = reader.ReadByte();
        SrcZoneNo = reader.ReadByte();
        CharLev = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserNo);
        writer.Write(CharNo);
        writer.Write(DestZoneNo);
        writer.Write(SrcZoneNo);
        writer.Write(CharLev);
    }
}

/// <summary>
/// Department: Syslog (0x32) | Opcode: 17 | Full: 0x3211
/// sizeof = 5
/// </summary>
[FiestaOpcode(ProtocolCommand.Syslog, 17)]
public class PROTO_NC_SYSLOG_SERVER_CCU : IFiestaPacketBody
{
    public uint UserCount;
    public byte WorldNo;

    public void Read(BinaryReader reader)
    {
        UserCount = reader.ReadUInt32();
        WorldNo = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(UserCount);
        writer.Write(WorldNo);
    }
}

