// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 8</summary>
public class PROTO_NC_TRADE_CENBOARDING_ACK
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_TRADE_DOWNBOARD_ACK
{
    public byte slotboard;

    public void Read(BinaryReader reader)
    {
        slotboard = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotboard);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_TRADE_DOWNBOARD_REQ
{
    public byte slotboard;

    public void Read(BinaryReader reader)
    {
        slotboard = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotboard);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_TRADE_OPPOSITCENBOARDING_CMD
{
    public ulong cen;

    public void Read(BinaryReader reader)
    {
        cen = reader.ReadUInt64();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(cen);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_TRADE_OPPOSITDOWNBOARD_CMD
{
    public byte slotboard;

    public void Read(BinaryReader reader)
    {
        slotboard = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotboard);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 104</summary>
public class PROTO_NC_TRADE_OPPOSITUPBOARD_CMD
{
    public byte slotboard;
    public SHINE_ITEM_STRUCT iteminfo = new();

    public void Read(BinaryReader reader)
    {
        slotboard = reader.ReadByte();
        iteminfo.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotboard);
        iteminfo.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_TRADE_PROPOSE_ASK_REQ
{
    public ushort proposer;

    public void Read(BinaryReader reader)
    {
        proposer = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(proposer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_TRADE_PROPOSE_REQ
{
    public ushort proposee;

    public void Read(BinaryReader reader)
    {
        proposee = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(proposee);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_TRADE_START_CMD
{
    public ushort opposite;

    public void Read(BinaryReader reader)
    {
        opposite = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(opposite);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_TRADE_UPBOARD_ACK
{
    public byte slotinven;
    public byte slotboard;

    public void Read(BinaryReader reader)
    {
        slotinven = reader.ReadByte();
        slotboard = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotinven);
        writer.Write(slotboard);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_TRADE_UPBOARD_REQ
{
    public byte slotinven;

    public void Read(BinaryReader reader)
    {
        slotinven = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(slotinven);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

