// <auto-generated />
namespace FiestaLibReloaded.Networking.Structs;

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_AVATAR_LIST_REQ
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_AVATARINFO_ACK
{
    public byte numofavatar;
    public PROTO_AVATARINFORMATION[] avatar = [];

    public void Read(BinaryReader reader)
    {
        numofavatar = reader.ReadByte();
        avatar = new PROTO_AVATARINFORMATION[numofavatar];
        for (int i = 0; i < numofavatar; i++)
        {
            avatar[i] = new PROTO_AVATARINFORMATION();
            avatar[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(numofavatar);
        for (int i = 0; i < avatar.Length; i++)
            avatar[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_USER_AVATARINFO_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public uint usrregnum;

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        usrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(usrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_USER_AVATARINFO_REQ_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_AVATARINFO_REQ req = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        req.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        req.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 287</summary>
public class PROTO_NC_USER_CH_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte id = new();
    public Name4 password = new();
    public uint usrregnum;
    public byte authid;
    public uint block;
    public uint loginable;

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        id.Read(reader);
        password.Read(reader);
        usrregnum = reader.ReadUInt32();
        authid = reader.ReadByte();
        block = reader.ReadUInt32();
        loginable = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        id.Write(writer);
        password.Write(writer);
        writer.Write(usrregnum);
        writer.Write(authid);
        writer.Write(block);
        writer.Write(loginable);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 290</summary>
public class PROTO_NC_USER_CH_PASSWORD_CHECK_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_CH_PASSWORD_CHECK_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 274</summary>
public class PROTO_NC_USER_CH_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte user = new();
    public Name4 password = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        user.Read(reader);
        password.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        user.Write(writer);
        password.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_CLIENT_RIGHTVERSION_CHECK_ACK
{
    public byte XTrapServerKeyLength;
    public byte[] XTrapServerKey = [];

    public void Read(BinaryReader reader)
    {
        XTrapServerKeyLength = reader.ReadByte();
        XTrapServerKey = reader.ReadBytes(XTrapServerKeyLength);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(XTrapServerKeyLength);
        writer.Write(XTrapServerKey);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 64</summary>
public class PROTO_NC_USER_CLIENT_VERSION_CHECK_REQ
{
    public sbyte[] sVersionKey = new sbyte[64];

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 64; i++)
            sVersionKey[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 64; i++)
            writer.Write(sVersionKey[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_CLIENT_WRONGVERSION_CHECK_ACK
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_USER_CONNECTCUT_CMD
{
    public ushort reason;

    public void Read(BinaryReader reader)
    {
        reason = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(reason);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 5</summary>
public class PROTO_NC_USER_CONNECTCUT_CMD_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_CONNECTCUT_CMD cmd = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        cmd.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        cmd.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_USER_CONNECTCUT2WORLDMANAGER_CMD
{
    public uint usrregnum;
    public ushort wldmanhandle;
    public ushort reason;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        wldmanhandle = reader.ReadUInt16();
        reason = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(wldmanhandle);
        writer.Write(reason);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_USER_CONNECTCUT2ZONE_CMD
{
    public uint usrregnum;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 13</summary>
public class PROTO_NC_USER_CONNECTCUT2ZONE_CMD_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public NETPACKETZONEHEADER netpacketzoneheader = new();
    public PROTO_NC_USER_CONNECTCUT2ZONE_CMD cmd = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        netpacketzoneheader.Read(reader);
        cmd.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        netpacketzoneheader.Write(writer);
        cmd.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 36</summary>
public class PROTO_NC_USER_CREATE_OTP_ACK
{
    public ushort nError;
    public ushort hWM;
    public Name8 sOTP = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        hWM = reader.ReadUInt16();
        sOTP.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        writer.Write(hWM);
        sOTP.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 266</summary>
public class PROTO_NC_USER_CREATE_OTP_REQ
{
    public ushort hWM;
    public uint nUserNo;
    public Name256Byte sUserID = new();
    public in_addr nClientIP = new();

    public void Read(BinaryReader reader)
    {
        hWM = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
        sUserID.Read(reader);
        nClientIP.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(hWM);
        writer.Write(nUserNo);
        sUserID.Write(writer);
        nClientIP.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 290</summary>
public class PROTO_NC_USER_GER_IS_IP_BLOCK_ACK
{
    public PROTO_NC_USER_GER_PASSWORD_CHECK_ACK LoginData = new();
    public ushort nClientHandle;
    public byte bUserIPBlock;

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nClientHandle = reader.ReadUInt16();
        bUserIPBlock = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nClientHandle);
        writer.Write(bUserIPBlock);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 313</summary>
public class PROTO_NC_USER_GER_IS_IP_BLOCK_REQ
{
    public PROTO_NC_USER_GER_PASSWORD_CHECK_ACK LoginData = new();
    public uint nUserNo;
    public ushort nClientHandle;
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nUserNo = reader.ReadUInt32();
        nClientHandle = reader.ReadUInt16();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nUserNo);
        writer.Write(nClientHandle);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 287</summary>
public class PROTO_NC_USER_GER_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte id = new();
    public Name4 password = new();
    public uint usrregnum;
    public byte authid;
    public uint block;
    public uint loginable;

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        id.Read(reader);
        password.Read(reader);
        usrregnum = reader.ReadUInt32();
        authid = reader.ReadByte();
        block = reader.ReadUInt32();
        loginable = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        id.Write(writer);
        password.Write(writer);
        writer.Write(usrregnum);
        writer.Write(authid);
        writer.Write(block);
        writer.Write(loginable);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 290</summary>
public class PROTO_NC_USER_GER_PASSWORD_CHECK_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_GER_PASSWORD_CHECK_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 274</summary>
public class PROTO_NC_USER_GER_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte user = new();
    public Name4 password = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        user.Read(reader);
        password.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        user.Write(writer);
        password.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 275</summary>
public class PROTO_NC_USER_IS_IP_BLOCK_ACK
{
    public PROTO_NC_USER_LOGIN_REQ LoginData = new();
    public ushort nClientHandle;
    public byte bUserIPBlock;

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nClientHandle = reader.ReadUInt16();
        bUserIPBlock = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nClientHandle);
        writer.Write(bUserIPBlock);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 298</summary>
public class PROTO_NC_USER_IS_IP_BLOCK_REQ
{
    public PROTO_NC_USER_LOGIN_REQ LoginData = new();
    public uint nUserNo;
    public ushort nClientHandle;
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nUserNo = reader.ReadUInt32();
        nClientHandle = reader.ReadUInt16();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nUserNo);
        writer.Write(nClientHandle);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 309</summary>
public class PROTO_NC_USER_JP_IS_IP_BLOCK_ACK
{
    public PROTO_NC_USER_JP_PASSWORD_CHECK_ACK LoginData = new();
    public ushort nClientHandle;
    public byte bUserIPBlock;

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nClientHandle = reader.ReadUInt16();
        bUserIPBlock = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nClientHandle);
        writer.Write(bUserIPBlock);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 332</summary>
public class PROTO_NC_USER_JP_IS_IP_BLOCK_REQ
{
    public PROTO_NC_USER_JP_PASSWORD_CHECK_ACK LoginData = new();
    public uint nUserNo;
    public ushort nClientHandle;
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nUserNo = reader.ReadUInt32();
        nClientHandle = reader.ReadUInt16();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nUserNo);
        writer.Write(nClientHandle);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 306</summary>
public class PROTO_NC_USER_JP_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public ushort nError;
    public uint nUserNo;
    public sbyte[] sUserName = new sbyte[24];
    public sbyte[] sChannel = new sbyte[254];
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        nError = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
        for (int i = 0; i < 24; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 254; i++)
            sChannel[i] = reader.ReadSByte();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(nError);
        writer.Write(nUserNo);
        for (int i = 0; i < 24; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 254; i++)
            writer.Write(sChannel[i]);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 336</summary>
public class PROTO_NC_USER_JP_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public sbyte[] sUserName = new sbyte[24];
    public sbyte[] sPassword = new sbyte[36];
    public sbyte[] sChannel = new sbyte[254];
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        for (int i = 0; i < 24; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 36; i++)
            sPassword[i] = reader.ReadSByte();
        for (int i = 0; i < 254; i++)
            sChannel[i] = reader.ReadSByte();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        for (int i = 0; i < 24; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 36; i++)
            writer.Write(sPassword[i]);
        for (int i = 0; i < 254; i++)
            writer.Write(sChannel[i]);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_USER_KICKOFFFROMWORLD_CMD
{
    public uint usrregnum;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 13</summary>
public class PROTO_NC_USER_KICKOFFFROMWORLD_CMD_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public NETPACKETZONEHEADER netpacketzoneheader = new();
    public PROTO_NC_USER_KICKOFFFROMWORLD_CMD cmd = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        netpacketzoneheader.Read(reader);
        cmd.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        netpacketzoneheader.Write(writer);
        cmd.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_LOGIN_ACK
{
    public byte numofworld;
    // PROTO_NC_USER_LOGIN_ACK::WorldInfo[0] worldinfo at offset 1 (unsupported type)

    public void Read(BinaryReader reader)
    {
        numofworld = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(numofworld);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_USER_LOGIN_DB
{
    public uint usrregnum;
    public byte worldnum;
    public byte[] ip = new byte[4];

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        ip = reader.ReadBytes(4);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(ip, 0, 4);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_USER_LOGIN_DB_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_LOGIN_DB db = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        db.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        db.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 278</summary>
public class PROTO_NC_USER_LOGIN_NETMARBLE_DB_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public byte[] UniID = new byte[20];
    public byte[] UserID = new byte[256];

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        UniID = reader.ReadBytes(20);
        UserID = reader.ReadBytes(256);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(UniID, 0, 20);
        writer.Write(UserID, 0, 256);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_USER_LOGIN_NETMARBLE_REQ
{
    public ushort CPCookieLength;
    public byte[] CPCookie = [];

    public void Read(BinaryReader reader)
    {
        CPCookieLength = reader.ReadUInt16();
        CPCookie = reader.ReadBytes(CPCookieLength);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(CPCookieLength);
        writer.Write(CPCookie);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 85</summary>
public class PROTO_NC_USER_LOGIN_OUTSPARK_REQ
{
    public byte[] LogonToken = new byte[65];
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        LogonToken = reader.ReadBytes(65);
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(LogonToken, 0, 65);
        spawnapps.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 272</summary>
public class PROTO_NC_USER_LOGIN_REQ
{
    public Name256Byte user = new();
    public Name4 password = new();

    public void Read(BinaryReader reader)
    {
        user.Read(reader);
        password.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        user.Write(writer);
        password.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 32</summary>
public class PROTO_NC_USER_LOGIN_WITH_OTP_REQ
{
    public Name8 sOTP = new();

    public void Read(BinaryReader reader)
    {
        sOTP.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        sOTP.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_USER_LOGINFAIL_ACK
{
    public ushort error;

    public void Read(BinaryReader reader)
    {
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 5</summary>
public class PROTO_NC_USER_LOGINFAIL_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_LOGINFAIL_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 3</summary>
public class PROTO_NC_USER_LOGINWORLD_ACK
{
    public ushort worldmanager;
    public byte numofavatar;
    public PROTO_AVATARINFORMATION[] avatar = [];

    public void Read(BinaryReader reader)
    {
        worldmanager = reader.ReadUInt16();
        numofavatar = reader.ReadByte();
        avatar = new PROTO_AVATARINFORMATION[numofavatar];
        for (int i = 0; i < numofavatar; i++)
        {
            avatar[i] = new PROTO_AVATARINFORMATION();
            avatar[i].Read(reader);
        }
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(worldmanager);
        writer.Write(numofavatar);
        for (int i = 0; i < avatar.Length; i++)
            avatar[i].Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 320</summary>
public class PROTO_NC_USER_LOGINWORLD_REQ
{
    public Name256Byte user = new();
    public ushort[] validate_new = new ushort[32];

    public void Read(BinaryReader reader)
    {
        user.Read(reader);
        for (int i = 0; i < 32; i++)
            validate_new[i] = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        user.Write(writer);
        for (int i = 0; i < 32; i++)
            writer.Write(validate_new[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 2</summary>
public class PROTO_NC_USER_LOGINWORLDFAIL_ACK
{
    public PROTO_ERRORCODE errorcode = new();

    public void Read(BinaryReader reader)
    {
        errorcode.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        errorcode.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 5</summary>
public class PROTO_NC_USER_LOGINWORLDFAIL_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_LOGINWORLDFAIL_ACK Ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        Ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        Ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 9</summary>
public class PROTO_NC_USER_LOGOUT_DB
{
    public uint usrregnum;
    public byte worldnum;
    public ushort playmin;
    public ushort error;

    public void Read(BinaryReader reader)
    {
        usrregnum = reader.ReadUInt32();
        worldnum = reader.ReadByte();
        playmin = reader.ReadUInt16();
        error = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(usrregnum);
        writer.Write(worldnum);
        writer.Write(playmin);
        writer.Write(error);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 12</summary>
public class PROTO_NC_USER_LOGOUT_DB_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_LOGOUT_DB db = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        db.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        db.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 10</summary>
public class PROTO_NC_USER_LOGOUT_LAST_DAY_ACK
{
    public ushort nHandle;
    public uint nUserNo;
    public int tLastSec;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
        tLastSec = reader.ReadInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nUserNo);
        writer.Write(tLastSec);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_USER_LOGOUT_LAST_DAY_REQ
{
    public ushort nHandle;
    public uint nUserNo;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nUserNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_NORMALLOGOUT_CMD
{
    public byte LogoutType;

    public void Read(BinaryReader reader)
    {
        LogoutType = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(LogoutType);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 287</summary>
public class PROTO_NC_USER_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte id = new();
    public Name4 password = new();
    public uint usrregnum;
    public byte authid;
    public uint block;
    public uint loginable;

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        id.Read(reader);
        password.Read(reader);
        usrregnum = reader.ReadUInt32();
        authid = reader.ReadByte();
        block = reader.ReadUInt32();
        loginable = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        id.Write(writer);
        password.Write(writer);
        writer.Write(usrregnum);
        writer.Write(authid);
        writer.Write(block);
        writer.Write(loginable);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 290</summary>
public class PROTO_NC_USER_PASSWORD_CHECK_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_PASSWORD_CHECK_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 274</summary>
public class PROTO_NC_USER_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public Name256Byte user = new();
    public Name4 password = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        user.Read(reader);
        password.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        user.Write(writer);
        password.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 277</summary>
public class PROTO_NC_USER_PASSWORD_CHECK_REQ_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_PASSWORD_CHECK_REQ req = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        req.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        req.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_USER_POSSIBLE_NEW_CONNECT_CMD
{
    public ushort nWorldManagerHandle;
    public uint nCharNo;

    public void Read(BinaryReader reader)
    {
        nWorldManagerHandle = reader.ReadUInt16();
        nCharNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nWorldManagerHandle);
        writer.Write(nCharNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_USER_REGISENUMBER_ACK
{
    public uint userregnum;

    public void Read(BinaryReader reader)
    {
        userregnum = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(userregnum);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 11</summary>
public class PROTO_NC_USER_RETURN_CHECK_ACK
{
    public ushort nHandle;
    public uint nUserNo;
    public byte bReturnUser;
    public int tLastSec;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
        bReturnUser = reader.ReadByte();
        tLastSec = reader.ReadInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nUserNo);
        writer.Write(bReturnUser);
        writer.Write(tLastSec);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 6</summary>
public class PROTO_NC_USER_RETURN_CHECK_REQ
{
    public ushort nHandle;
    public uint nUserNo;

    public void Read(BinaryReader reader)
    {
        nHandle = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nHandle);
        writer.Write(nUserNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 4</summary>
public class PROTO_NC_USER_SET_RETURN_CMD
{
    public uint nUserNo;

    public void Read(BinaryReader reader)
    {
        nUserNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nUserNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 313</summary>
public class PROTO_NC_USER_TEENAGER_ACK
{
    public Name256Byte sUserID = new();
    public ushort nHandle;
    public PROTO_NC_USER_TEENAGER_CMD Data = new();

    public void Read(BinaryReader reader)
    {
        sUserID.Read(reader);
        nHandle = reader.ReadUInt16();
        Data.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        sUserID.Write(writer);
        writer.Write(nHandle);
        Data.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 55</summary>
public class PROTO_NC_USER_TEENAGER_CMD
{
    public byte[] sUserKey = new byte[50];
    public byte nType;
    public uint nMinute;

    public void Read(BinaryReader reader)
    {
        sUserKey = reader.ReadBytes(50);
        nType = reader.ReadByte();
        nMinute = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(sUserKey, 0, 50);
        writer.Write(nType);
        writer.Write(nMinute);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 258</summary>
public class PROTO_NC_USER_TEENAGER_REQ
{
    public Name256Byte sUserID = new();
    public ushort nHandle;

    public void Read(BinaryReader reader)
    {
        sUserID.Read(reader);
        nHandle = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        sUserID.Write(writer);
        writer.Write(nHandle);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 54</summary>
public class PROTO_NC_USER_TEENAGER_SET_CMD
{
    public byte[] sUserKey = new byte[50];
    public uint nUserPlayRemainTime;

    public void Read(BinaryReader reader)
    {
        sUserKey = reader.ReadBytes(50);
        nUserPlayRemainTime = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(sUserKey, 0, 50);
        writer.Write(nUserPlayRemainTime);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_TUTORIAL_CAN_SKIP_CMD
{
    public byte bCanSkip;

    public void Read(BinaryReader reader)
    {
        bCanSkip = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(bCanSkip);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 11</summary>
public class PROTO_NC_USER_TW_IS_IP_BLOCK_ACK
{
    public PROTO_NC_USER_TW_PASSWORD_CHECK_ACK LoginData = new();
    public ushort nClientHandle;
    public byte bUserIPBlock;

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nClientHandle = reader.ReadUInt16();
        bUserIPBlock = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nClientHandle);
        writer.Write(bUserIPBlock);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_USER_TW_IS_IP_BLOCK_REQ
{
    public PROTO_NC_USER_TW_PASSWORD_CHECK_ACK LoginData = new();
    public uint nUserNo;
    public ushort nClientHandle;
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nUserNo = reader.ReadUInt32();
        nClientHandle = reader.ReadUInt16();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nUserNo);
        writer.Write(nClientHandle);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 8</summary>
public class PROTO_NC_USER_TW_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public ushort nError;
    public uint nUserNo;

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        nError = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(nError);
        writer.Write(nUserNo);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 11</summary>
public class PROTO_NC_USER_TW_PASSWORD_CHECK_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_TW_PASSWORD_CHECK_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 102</summary>
public class PROTO_NC_USER_TW_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public sbyte[] sUserName = new sbyte[36];
    public sbyte[] sSerial = new sbyte[36];
    public sbyte[] sUID = new sbyte[20];
    public sbyte[] sSID = new sbyte[8];

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        for (int i = 0; i < 36; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 36; i++)
            sSerial[i] = reader.ReadSByte();
        for (int i = 0; i < 20; i++)
            sUID[i] = reader.ReadSByte();
        for (int i = 0; i < 8; i++)
            sSID[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        for (int i = 0; i < 36; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 36; i++)
            writer.Write(sSerial[i]);
        for (int i = 0; i < 20; i++)
            writer.Write(sUID[i]);
        for (int i = 0; i < 8; i++)
            writer.Write(sSID[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 356</summary>
public class PROTO_NC_USER_US_IS_IP_BLOCK_ACK
{
    public PROTO_NC_USER_US_PASSWORD_CHECK_ACK LoginData = new();
    public ushort nClientHandle;
    public byte bUserIPBlock;

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nClientHandle = reader.ReadUInt16();
        bUserIPBlock = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nClientHandle);
        writer.Write(bUserIPBlock);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 379</summary>
public class PROTO_NC_USER_US_IS_IP_BLOCK_REQ
{
    public PROTO_NC_USER_US_PASSWORD_CHECK_ACK LoginData = new();
    public uint nUserNo;
    public ushort nClientHandle;
    public sbyte[] sUserIP = new sbyte[20];

    public void Read(BinaryReader reader)
    {
        LoginData.Read(reader);
        nUserNo = reader.ReadUInt32();
        nClientHandle = reader.ReadUInt16();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
    }

    public void Write(BinaryWriter writer)
    {
        LoginData.Write(writer);
        writer.Write(nUserNo);
        writer.Write(nClientHandle);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 316</summary>
public class PROTO_NC_USER_US_LOGIN_REQ
{
    public sbyte[] sUserName = new sbyte[260];
    public sbyte[] sPassword = new sbyte[36];
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        for (int i = 0; i < 260; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 36; i++)
            sPassword[i] = reader.ReadSByte();
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        for (int i = 0; i < 260; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 36; i++)
            writer.Write(sPassword[i]);
        spawnapps.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 353</summary>
public class PROTO_NC_USER_US_PASSWORD_CHECK_ACK
{
    public NETPACKETHEADER netpacketheader = new();
    public ushort nError;
    public uint nUserNo;
    public sbyte[] sUserName = new sbyte[260];
    public sbyte[] sPassword = new sbyte[36];
    public sbyte[] sUserIP = new sbyte[20];
    public byte nAuthID;
    public uint nBlock;
    public uint bLoginAble;
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        nError = reader.ReadUInt16();
        nUserNo = reader.ReadUInt32();
        for (int i = 0; i < 260; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 36; i++)
            sPassword[i] = reader.ReadSByte();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
        nAuthID = reader.ReadByte();
        nBlock = reader.ReadUInt32();
        bLoginAble = reader.ReadUInt32();
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(nError);
        writer.Write(nUserNo);
        for (int i = 0; i < 260; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 36; i++)
            writer.Write(sPassword[i]);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
        writer.Write(nAuthID);
        writer.Write(nBlock);
        writer.Write(bLoginAble);
        spawnapps.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 338</summary>
public class PROTO_NC_USER_US_PASSWORD_CHECK_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public sbyte[] sUserName = new sbyte[260];
    public sbyte[] sPassword = new sbyte[36];
    public sbyte[] sUserIP = new sbyte[20];
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        for (int i = 0; i < 260; i++)
            sUserName[i] = reader.ReadSByte();
        for (int i = 0; i < 36; i++)
            sPassword[i] = reader.ReadSByte();
        for (int i = 0; i < 20; i++)
            sUserIP[i] = reader.ReadSByte();
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        for (int i = 0; i < 260; i++)
            writer.Write(sUserName[i]);
        for (int i = 0; i < 36; i++)
            writer.Write(sPassword[i]);
        for (int i = 0; i < 20; i++)
            writer.Write(sUserIP[i]);
        spawnapps.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_USE_BEAUTY_SHOP_CMD
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 34</summary>
public class PROTO_NC_USER_WILL_WORLD_SELECT_ACK
{
    public ushort nError;
    public Name8 sOTP = new();

    public void Read(BinaryReader reader)
    {
        nError = reader.ReadUInt16();
        sOTP.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(nError);
        sOTP.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_WILL_WORLD_SELECT_REQ
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 348</summary>
public class PROTO_NC_USER_WILLLOGIN_ACK
{
    public PROTO_NC_USER_WILLLOGIN_REQ will_login_req = new();
    public byte ok;

    public void Read(BinaryReader reader)
    {
        will_login_req.Read(reader);
        ok = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        will_login_req.Write(writer);
        writer.Write(ok);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 347</summary>
public class PROTO_NC_USER_WILLLOGIN_REQ
{
    public NETPACKETHEADER netpacketheader = new();
    public byte willlogin_worldno;
    public uint usrregnum;
    public Name256Byte userid = new();
    public ushort[] validate_new = new ushort[32];
    public Name5 spawnapps = new();

    public void Read(BinaryReader reader)
    {
        netpacketheader.Read(reader);
        willlogin_worldno = reader.ReadByte();
        usrregnum = reader.ReadUInt32();
        userid.Read(reader);
        for (int i = 0; i < 32; i++)
            validate_new[i] = reader.ReadUInt16();
        spawnapps.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        netpacketheader.Write(writer);
        writer.Write(willlogin_worldno);
        writer.Write(usrregnum);
        userid.Write(writer);
        for (int i = 0; i < 32; i++)
            writer.Write(validate_new[i]);
        spawnapps.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_WORLD_STATUS_REQ
{

    public void Read(BinaryReader reader)
    {
    }

    public void Write(BinaryWriter writer)
    {
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 83</summary>
public class PROTO_NC_USER_WORLDSELECT_ACK
{
    public byte worldstatus;
    public Name4 ip = new();
    public ushort port;
    public ushort[] validate_new = new ushort[32];

    public void Read(BinaryReader reader)
    {
        worldstatus = reader.ReadByte();
        ip.Read(reader);
        port = reader.ReadUInt16();
        for (int i = 0; i < 32; i++)
            validate_new[i] = reader.ReadUInt16();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(worldstatus);
        ip.Write(writer);
        writer.Write(port);
        for (int i = 0; i < 32; i++)
            writer.Write(validate_new[i]);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 86</summary>
public class PROTO_NC_USER_WORLDSELECT_ACK_SEND
{
    public byte size;
    public NETCOMMAND netcmd = new();
    public PROTO_NC_USER_WORLDSELECT_ACK ack = new();

    public void Read(BinaryReader reader)
    {
        size = reader.ReadByte();
        netcmd.Read(reader);
        ack.Read(reader);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(size);
        netcmd.Write(writer);
        ack.Write(writer);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_WORLDSELECT_REQ
{
    public byte worldno;

    public void Read(BinaryReader reader)
    {
        worldno = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(worldno);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_XTRAP_ACK
{
    public byte bSuccess;

    public void Read(BinaryReader reader)
    {
        bSuccess = reader.ReadByte();
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(bSuccess);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

/// <summary>sizeof = 1</summary>
public class PROTO_NC_USER_XTRAP_REQ
{
    public byte XTrapClientKeyLength;
    public byte[] XTrapClientKey = [];

    public void Read(BinaryReader reader)
    {
        XTrapClientKeyLength = reader.ReadByte();
        XTrapClientKey = reader.ReadBytes(XTrapClientKeyLength);
    }

    public void Write(BinaryWriter writer)
    {
        writer.Write(XTrapClientKeyLength);
        writer.Write(XTrapClientKey);
    }

    public void Read(Stream stream) => Read(new BinaryReader(stream, System.Text.Encoding.UTF8, true));
    public void Write(Stream stream) => Write(new BinaryWriter(stream, System.Text.Encoding.UTF8, true));
}

